/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Body17
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class Body17 {
  @SerializedName("mer_id")
  private String merId = null;

  @SerializedName("custid")
  private String custid = null;

  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  @SerializedName("requesttype")
  private String requesttype = null;

  @SerializedName("authtoken")
  private BigDecimal authtoken = null;

  @SerializedName("requestdeviceid")
  private String requestdeviceid = null;

  @SerializedName("csrftoken")
  private String csrftoken = null;

  public Body17 merId(String merId) {
    this.merId = merId;
    return this;
  }

   /**
   * Get merId
   * @return merId
  **/
  @Schema(description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }

  public Body17 custid(String custid) {
    this.custid = custid;
    return this;
  }

   /**
   * Get custid
   * @return custid
  **/
  @Schema(description = "")
  public String getCustid() {
    return custid;
  }

  public void setCustid(String custid) {
    this.custid = custid;
  }

  public Body17 sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
  @Schema(required = true, description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }

  public Body17 requesttype(String requesttype) {
    this.requesttype = requesttype;
    return this;
  }

   /**
   * Get requesttype
   * @return requesttype
  **/
  @Schema(required = true, description = "")
  public String getRequesttype() {
    return requesttype;
  }

  public void setRequesttype(String requesttype) {
    this.requesttype = requesttype;
  }

  public Body17 authtoken(BigDecimal authtoken) {
    this.authtoken = authtoken;
    return this;
  }

   /**
   * Get authtoken
   * minimum: 111111
   * maximum: 999999
   * @return authtoken
  **/
  @Schema(required = true, description = "")
  public BigDecimal getAuthtoken() {
    return authtoken;
  }

  public void setAuthtoken(BigDecimal authtoken) {
    this.authtoken = authtoken;
  }

  public Body17 requestdeviceid(String requestdeviceid) {
    this.requestdeviceid = requestdeviceid;
    return this;
  }

   /**
   * Get requestdeviceid
   * @return requestdeviceid
  **/
  @Schema(required = true, description = "")
  public String getRequestdeviceid() {
    return requestdeviceid;
  }

  public void setRequestdeviceid(String requestdeviceid) {
    this.requestdeviceid = requestdeviceid;
  }

  public Body17 csrftoken(String csrftoken) {
    this.csrftoken = csrftoken;
    return this;
  }

   /**
   * Get csrftoken
   * @return csrftoken
  **/
  @Schema(description = "")
  public String getCsrftoken() {
    return csrftoken;
  }

  public void setCsrftoken(String csrftoken) {
    this.csrftoken = csrftoken;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body17 body17 = (Body17) o;
    return Objects.equals(this.merId, body17.merId) &&
        Objects.equals(this.custid, body17.custid) &&
        Objects.equals(this.sessiontoken, body17.sessiontoken) &&
        Objects.equals(this.requesttype, body17.requesttype) &&
        Objects.equals(this.authtoken, body17.authtoken) &&
        Objects.equals(this.requestdeviceid, body17.requestdeviceid) &&
        Objects.equals(this.csrftoken, body17.csrftoken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merId, custid, sessiontoken, requesttype, authtoken, requestdeviceid, csrftoken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body17 {\n");

    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("    custid: ").append(toIndentedString(custid)).append("\n");
    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("    requesttype: ").append(toIndentedString(requesttype)).append("\n");
    sb.append("    authtoken: ").append(toIndentedString(authtoken)).append("\n");
    sb.append("    requestdeviceid: ").append(toIndentedString(requestdeviceid)).append("\n");
    sb.append("    csrftoken: ").append(toIndentedString(csrftoken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
