/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Body5
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class Body5 {
  @SerializedName("cust_id")
  private String custId = null;

  @SerializedName("mobile_no")
  private String mobileNo = null;

  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  @SerializedName("otp")
  private String otp = null;

  @SerializedName("otp_identifier")
  private String otpIdentifier = null;

  @SerializedName("request_type")
  private String requestType = null;

  @SerializedName("device_id")
  private String deviceId = null;

  public Body5 custId(String custId) {
    this.custId = custId;
    return this;
  }

   /**
   * Get custId
   * @return custId
  **/
  @Schema(required = true, description = "")
  public String getCustId() {
    return custId;
  }

  public void setCustId(String custId) {
    this.custId = custId;
  }

  public Body5 mobileNo(String mobileNo) {
    this.mobileNo = mobileNo;
    return this;
  }

   /**
   * Get mobileNo
   * @return mobileNo
  **/
  @Schema(required = true, description = "")
  public String getMobileNo() {
    return mobileNo;
  }

  public void setMobileNo(String mobileNo) {
    this.mobileNo = mobileNo;
  }

  public Body5 sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
  @Schema(description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }

  public Body5 otp(String otp) {
    this.otp = otp;
    return this;
  }

   /**
   * Get otp
   * @return otp
  **/
  @Schema(description = "")
  public String getOtp() {
    return otp;
  }

  public void setOtp(String otp) {
    this.otp = otp;
  }

  public Body5 otpIdentifier(String otpIdentifier) {
    this.otpIdentifier = otpIdentifier;
    return this;
  }

   /**
   * Get otpIdentifier
   * @return otpIdentifier
  **/
  @Schema(description = "")
  public String getOtpIdentifier() {
    return otpIdentifier;
  }

  public void setOtpIdentifier(String otpIdentifier) {
    this.otpIdentifier = otpIdentifier;
  }

  public Body5 requestType(String requestType) {
    this.requestType = requestType;
    return this;
  }

   /**
   * Get requestType
   * @return requestType
  **/
  @Schema(description = "")
  public String getRequestType() {
    return requestType;
  }

  public void setRequestType(String requestType) {
    this.requestType = requestType;
  }

  public Body5 deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Get deviceId
   * @return deviceId
  **/
  @Schema(description = "")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body5 body5 = (Body5) o;
    return Objects.equals(this.custId, body5.custId) &&
        Objects.equals(this.mobileNo, body5.mobileNo) &&
        Objects.equals(this.sessiontoken, body5.sessiontoken) &&
        Objects.equals(this.otp, body5.otp) &&
        Objects.equals(this.otpIdentifier, body5.otpIdentifier) &&
        Objects.equals(this.requestType, body5.requestType) &&
        Objects.equals(this.deviceId, body5.deviceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(custId, mobileNo, sessiontoken, otp, otpIdentifier, requestType, deviceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body5 {\n");

    sb.append("    custId: ").append(toIndentedString(custId)).append("\n");
    sb.append("    mobileNo: ").append(toIndentedString(mobileNo)).append("\n");
    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("    otp: ").append(toIndentedString(otp)).append("\n");
    sb.append("    otpIdentifier: ").append(toIndentedString(otpIdentifier)).append("\n");
    sb.append("    requestType: ").append(toIndentedString(requestType)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
