/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Body2
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class Body2 {
  @SerializedName("device_id")
  private String deviceId = null;

  @SerializedName("mer_id")
  private String merId = null;

  @SerializedName("device_model")
  private String deviceModel = null;

  @SerializedName("os_version")
  private String osVersion = null;

  @SerializedName("screen_res")
  private String screenRes = null;

  @SerializedName("tnc_accept_dttm")
  private String tncAcceptDttm = null;

  @SerializedName("mobile_no")
  private String mobileNo = null;

  @SerializedName("registration_type")
  private String registrationType = null;

  @SerializedName("notify_instance_id")
  private String notifyInstanceId = null;

  public Body2 deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Get deviceId
   * @return deviceId
  **/
  @Schema(description = "")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public Body2 merId(String merId) {
    this.merId = merId;
    return this;
  }

   /**
   * Get merId
   * @return merId
  **/
  @Schema(description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }

  public Body2 deviceModel(String deviceModel) {
    this.deviceModel = deviceModel;
    return this;
  }

   /**
   * Get deviceModel
   * @return deviceModel
  **/
  @Schema(required = true, description = "")
  public String getDeviceModel() {
    return deviceModel;
  }

  public void setDeviceModel(String deviceModel) {
    this.deviceModel = deviceModel;
  }

  public Body2 osVersion(String osVersion) {
    this.osVersion = osVersion;
    return this;
  }

   /**
   * Get osVersion
   * @return osVersion
  **/
  @Schema(required = true, description = "")
  public String getOsVersion() {
    return osVersion;
  }

  public void setOsVersion(String osVersion) {
    this.osVersion = osVersion;
  }

  public Body2 screenRes(String screenRes) {
    this.screenRes = screenRes;
    return this;
  }

   /**
   * Get screenRes
   * @return screenRes
  **/
  @Schema(required = true, description = "")
  public String getScreenRes() {
    return screenRes;
  }

  public void setScreenRes(String screenRes) {
    this.screenRes = screenRes;
  }

  public Body2 tncAcceptDttm(String tncAcceptDttm) {
    this.tncAcceptDttm = tncAcceptDttm;
    return this;
  }

   /**
   * Get tncAcceptDttm
   * @return tncAcceptDttm
  **/
  @Schema(required = true, description = "")
  public String getTncAcceptDttm() {
    return tncAcceptDttm;
  }

  public void setTncAcceptDttm(String tncAcceptDttm) {
    this.tncAcceptDttm = tncAcceptDttm;
  }

  public Body2 mobileNo(String mobileNo) {
    this.mobileNo = mobileNo;
    return this;
  }

   /**
   * Get mobileNo
   * @return mobileNo
  **/
  @Schema(description = "")
  public String getMobileNo() {
    return mobileNo;
  }

  public void setMobileNo(String mobileNo) {
    this.mobileNo = mobileNo;
  }

  public Body2 registrationType(String registrationType) {
    this.registrationType = registrationType;
    return this;
  }

   /**
   * Get registrationType
   * @return registrationType
  **/
  @Schema(description = "")
  public String getRegistrationType() {
    return registrationType;
  }

  public void setRegistrationType(String registrationType) {
    this.registrationType = registrationType;
  }

  public Body2 notifyInstanceId(String notifyInstanceId) {
    this.notifyInstanceId = notifyInstanceId;
    return this;
  }

   /**
   * Get notifyInstanceId
   * @return notifyInstanceId
  **/
  @Schema(description = "")
  public String getNotifyInstanceId() {
    return notifyInstanceId;
  }

  public void setNotifyInstanceId(String notifyInstanceId) {
    this.notifyInstanceId = notifyInstanceId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body2 body2 = (Body2) o;
    return Objects.equals(this.deviceId, body2.deviceId) &&
        Objects.equals(this.merId, body2.merId) &&
        Objects.equals(this.deviceModel, body2.deviceModel) &&
        Objects.equals(this.osVersion, body2.osVersion) &&
        Objects.equals(this.screenRes, body2.screenRes) &&
        Objects.equals(this.tncAcceptDttm, body2.tncAcceptDttm) &&
        Objects.equals(this.mobileNo, body2.mobileNo) &&
        Objects.equals(this.registrationType, body2.registrationType) &&
        Objects.equals(this.notifyInstanceId, body2.notifyInstanceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceId, merId, deviceModel, osVersion, screenRes, tncAcceptDttm, mobileNo, registrationType, notifyInstanceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body2 {\n");

    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("    deviceModel: ").append(toIndentedString(deviceModel)).append("\n");
    sb.append("    osVersion: ").append(toIndentedString(osVersion)).append("\n");
    sb.append("    screenRes: ").append(toIndentedString(screenRes)).append("\n");
    sb.append("    tncAcceptDttm: ").append(toIndentedString(tncAcceptDttm)).append("\n");
    sb.append("    mobileNo: ").append(toIndentedString(mobileNo)).append("\n");
    sb.append("    registrationType: ").append(toIndentedString(registrationType)).append("\n");
    sb.append("    notifyInstanceId: ").append(toIndentedString(notifyInstanceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
