/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Body25
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class Body25 {
  @SerializedName("device_id")
  private String deviceId = null;

  @SerializedName("mer_id")
  private String merId = null;

  @SerializedName("req_type")
  private String reqType = null;

  @SerializedName("req_value")
  private String reqValue = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("text")
  private String text = null;

  @SerializedName("image_url")
  private String imageUrl = null;

  @SerializedName("send_dt")
  private String sendDt = null;

  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  @SerializedName("key_value")
  private List<MerchantcreateschedulenotificationKeyValue> keyValue = null;

  public Body25 deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Get deviceId
   * @return deviceId
  **/
  @Schema(required = true, description = "")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public Body25 merId(String merId) {
    this.merId = merId;
    return this;
  }

   /**
   * Get merId
   * @return merId
  **/
  @Schema(required = true, description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }

  public Body25 reqType(String reqType) {
    this.reqType = reqType;
    return this;
  }

   /**
   * Get reqType
   * @return reqType
  **/
  @Schema(required = true, description = "")
  public String getReqType() {
    return reqType;
  }

  public void setReqType(String reqType) {
    this.reqType = reqType;
  }

  public Body25 reqValue(String reqValue) {
    this.reqValue = reqValue;
    return this;
  }

   /**
   * Get reqValue
   * @return reqValue
  **/
  @Schema(description = "")
  public String getReqValue() {
    return reqValue;
  }

  public void setReqValue(String reqValue) {
    this.reqValue = reqValue;
  }

  public Body25 title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(required = true, description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Body25 text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  @Schema(required = true, description = "")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public Body25 imageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
    return this;
  }

   /**
   * Get imageUrl
   * @return imageUrl
  **/
  @Schema(description = "")
  public String getImageUrl() {
    return imageUrl;
  }

  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  public Body25 sendDt(String sendDt) {
    this.sendDt = sendDt;
    return this;
  }

   /**
   * Get sendDt
   * @return sendDt
  **/
  @Schema(description = "")
  public String getSendDt() {
    return sendDt;
  }

  public void setSendDt(String sendDt) {
    this.sendDt = sendDt;
  }

  public Body25 sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
  @Schema(description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }

  public Body25 keyValue(List<MerchantcreateschedulenotificationKeyValue> keyValue) {
    this.keyValue = keyValue;
    return this;
  }

  public Body25 addKeyValueItem(MerchantcreateschedulenotificationKeyValue keyValueItem) {
    if (this.keyValue == null) {
      this.keyValue = new ArrayList<MerchantcreateschedulenotificationKeyValue>();
    }
    this.keyValue.add(keyValueItem);
    return this;
  }

   /**
   * Get keyValue
   * @return keyValue
  **/
  @Schema(description = "")
  public List<MerchantcreateschedulenotificationKeyValue> getKeyValue() {
    return keyValue;
  }

  public void setKeyValue(List<MerchantcreateschedulenotificationKeyValue> keyValue) {
    this.keyValue = keyValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body25 body25 = (Body25) o;
    return Objects.equals(this.deviceId, body25.deviceId) &&
        Objects.equals(this.merId, body25.merId) &&
        Objects.equals(this.reqType, body25.reqType) &&
        Objects.equals(this.reqValue, body25.reqValue) &&
        Objects.equals(this.title, body25.title) &&
        Objects.equals(this.text, body25.text) &&
        Objects.equals(this.imageUrl, body25.imageUrl) &&
        Objects.equals(this.sendDt, body25.sendDt) &&
        Objects.equals(this.sessiontoken, body25.sessiontoken) &&
        Objects.equals(this.keyValue, body25.keyValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceId, merId, reqType, reqValue, title, text, imageUrl, sendDt, sessiontoken, keyValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body25 {\n");

    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("    reqType: ").append(toIndentedString(reqType)).append("\n");
    sb.append("    reqValue: ").append(toIndentedString(reqValue)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("    sendDt: ").append(toIndentedString(sendDt)).append("\n");
    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("    keyValue: ").append(toIndentedString(keyValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
