/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Body6
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class Body6 {
  @SerializedName("device_id")
  private String deviceId = null;

  @SerializedName("cust_id")
  private String custId = null;

  @SerializedName("mer_id")
  private String merId = null;

  @SerializedName("outlet_id")
  private String outletId = null;

  @SerializedName("pay_amt")
  private String payAmt = null;

  @SerializedName("wallet_bal")
  private String walletBal = null;

  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  @SerializedName("authtoken")
  private String authtoken = null;

  public Body6 deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Get deviceId
   * @return deviceId
  **/
  @Schema(description = "")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public Body6 custId(String custId) {
    this.custId = custId;
    return this;
  }

   /**
   * Get custId
   * @return custId
  **/
  @Schema(required = true, description = "")
  public String getCustId() {
    return custId;
  }

  public void setCustId(String custId) {
    this.custId = custId;
  }

  public Body6 merId(String merId) {
    this.merId = merId;
    return this;
  }

   /**
   * Get merId
   * @return merId
  **/
  @Schema(required = true, description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }

  public Body6 outletId(String outletId) {
    this.outletId = outletId;
    return this;
  }

   /**
   * Get outletId
   * @return outletId
  **/
  @Schema(description = "")
  public String getOutletId() {
    return outletId;
  }

  public void setOutletId(String outletId) {
    this.outletId = outletId;
  }

  public Body6 payAmt(String payAmt) {
    this.payAmt = payAmt;
    return this;
  }

   /**
   * Get payAmt
   * @return payAmt
  **/
  @Schema(required = true, description = "")
  public String getPayAmt() {
    return payAmt;
  }

  public void setPayAmt(String payAmt) {
    this.payAmt = payAmt;
  }

  public Body6 walletBal(String walletBal) {
    this.walletBal = walletBal;
    return this;
  }

   /**
   * Get walletBal
   * @return walletBal
  **/
  @Schema(description = "")
  public String getWalletBal() {
    return walletBal;
  }

  public void setWalletBal(String walletBal) {
    this.walletBal = walletBal;
  }

  public Body6 sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
  @Schema(required = true, description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }

  public Body6 authtoken(String authtoken) {
    this.authtoken = authtoken;
    return this;
  }

   /**
   * Get authtoken
   * @return authtoken
  **/
  @Schema(description = "")
  public String getAuthtoken() {
    return authtoken;
  }

  public void setAuthtoken(String authtoken) {
    this.authtoken = authtoken;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body6 body6 = (Body6) o;
    return Objects.equals(this.deviceId, body6.deviceId) &&
        Objects.equals(this.custId, body6.custId) &&
        Objects.equals(this.merId, body6.merId) &&
        Objects.equals(this.outletId, body6.outletId) &&
        Objects.equals(this.payAmt, body6.payAmt) &&
        Objects.equals(this.walletBal, body6.walletBal) &&
        Objects.equals(this.sessiontoken, body6.sessiontoken) &&
        Objects.equals(this.authtoken, body6.authtoken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceId, custId, merId, outletId, payAmt, walletBal, sessiontoken, authtoken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body6 {\n");

    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    custId: ").append(toIndentedString(custId)).append("\n");
    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("    outletId: ").append(toIndentedString(outletId)).append("\n");
    sb.append("    payAmt: ").append(toIndentedString(payAmt)).append("\n");
    sb.append("    walletBal: ").append(toIndentedString(walletBal)).append("\n");
    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("    authtoken: ").append(toIndentedString(authtoken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
