/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Body21
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class Body21 {
  @SerializedName("mer_id")
  private String merId = null;

  @SerializedName("mobile_no")
  private String mobileNo = null;

  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  @SerializedName("pay_amt")
  private String payAmt = null;

  @SerializedName("device_id")
  private String deviceId = null;

  @SerializedName("outlet_id")
  private String outletId = null;

  public Body21 merId(String merId) {
    this.merId = merId;
    return this;
  }

   /**
   * Get merId
   * @return merId
  **/
  @Schema(required = true, description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }

  public Body21 mobileNo(String mobileNo) {
    this.mobileNo = mobileNo;
    return this;
  }

   /**
   * Get mobileNo
   * @return mobileNo
  **/
  @Schema(description = "")
  public String getMobileNo() {
    return mobileNo;
  }

  public void setMobileNo(String mobileNo) {
    this.mobileNo = mobileNo;
  }

  public Body21 sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
  @Schema(description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }

  public Body21 payAmt(String payAmt) {
    this.payAmt = payAmt;
    return this;
  }

   /**
   * Get payAmt
   * @return payAmt
  **/
  @Schema(description = "")
  public String getPayAmt() {
    return payAmt;
  }

  public void setPayAmt(String payAmt) {
    this.payAmt = payAmt;
  }

  public Body21 deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Get deviceId
   * @return deviceId
  **/
  @Schema(required = true, description = "")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public Body21 outletId(String outletId) {
    this.outletId = outletId;
    return this;
  }

   /**
   * Get outletId
   * @return outletId
  **/
  @Schema(description = "")
  public String getOutletId() {
    return outletId;
  }

  public void setOutletId(String outletId) {
    this.outletId = outletId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body21 body21 = (Body21) o;
    return Objects.equals(this.merId, body21.merId) &&
        Objects.equals(this.mobileNo, body21.mobileNo) &&
        Objects.equals(this.sessiontoken, body21.sessiontoken) &&
        Objects.equals(this.payAmt, body21.payAmt) &&
        Objects.equals(this.deviceId, body21.deviceId) &&
        Objects.equals(this.outletId, body21.outletId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merId, mobileNo, sessiontoken, payAmt, deviceId, outletId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body21 {\n");

    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("    mobileNo: ").append(toIndentedString(mobileNo)).append("\n");
    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("    payAmt: ").append(toIndentedString(payAmt)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    outletId: ").append(toIndentedString(outletId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
