/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Body14
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class Body14 {
  @SerializedName("deviceid")
  private String deviceid = null;

  @SerializedName("mer_id")
  private String merId = null;

  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  @SerializedName("campaign_redemption_stats_flag")
  private String campaignRedemptionStatsFlag = null;

  @SerializedName("customer_stats_flag")
  private String customerStatsFlag = null;

  @SerializedName("new_customers_by_month_flag")
  private String newCustomersByMonthFlag = null;

  public Body14 deviceid(String deviceid) {
    this.deviceid = deviceid;
    return this;
  }

   /**
   * Get deviceid
   * @return deviceid
  **/
  @Schema(required = true, description = "")
  public String getDeviceid() {
    return deviceid;
  }

  public void setDeviceid(String deviceid) {
    this.deviceid = deviceid;
  }

  public Body14 merId(String merId) {
    this.merId = merId;
    return this;
  }

   /**
   * Get merId
   * @return merId
  **/
  @Schema(required = true, description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }

  public Body14 sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
  @Schema(required = true, description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }

  public Body14 campaignRedemptionStatsFlag(String campaignRedemptionStatsFlag) {
    this.campaignRedemptionStatsFlag = campaignRedemptionStatsFlag;
    return this;
  }

   /**
   * Get campaignRedemptionStatsFlag
   * @return campaignRedemptionStatsFlag
  **/
  @Schema(description = "")
  public String getCampaignRedemptionStatsFlag() {
    return campaignRedemptionStatsFlag;
  }

  public void setCampaignRedemptionStatsFlag(String campaignRedemptionStatsFlag) {
    this.campaignRedemptionStatsFlag = campaignRedemptionStatsFlag;
  }

  public Body14 customerStatsFlag(String customerStatsFlag) {
    this.customerStatsFlag = customerStatsFlag;
    return this;
  }

   /**
   * Get customerStatsFlag
   * @return customerStatsFlag
  **/
  @Schema(description = "")
  public String getCustomerStatsFlag() {
    return customerStatsFlag;
  }

  public void setCustomerStatsFlag(String customerStatsFlag) {
    this.customerStatsFlag = customerStatsFlag;
  }

  public Body14 newCustomersByMonthFlag(String newCustomersByMonthFlag) {
    this.newCustomersByMonthFlag = newCustomersByMonthFlag;
    return this;
  }

   /**
   * Get newCustomersByMonthFlag
   * @return newCustomersByMonthFlag
  **/
  @Schema(description = "")
  public String getNewCustomersByMonthFlag() {
    return newCustomersByMonthFlag;
  }

  public void setNewCustomersByMonthFlag(String newCustomersByMonthFlag) {
    this.newCustomersByMonthFlag = newCustomersByMonthFlag;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body14 body14 = (Body14) o;
    return Objects.equals(this.deviceid, body14.deviceid) &&
        Objects.equals(this.merId, body14.merId) &&
        Objects.equals(this.sessiontoken, body14.sessiontoken) &&
        Objects.equals(this.campaignRedemptionStatsFlag, body14.campaignRedemptionStatsFlag) &&
        Objects.equals(this.customerStatsFlag, body14.customerStatsFlag) &&
        Objects.equals(this.newCustomersByMonthFlag, body14.newCustomersByMonthFlag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceid, merId, sessiontoken, campaignRedemptionStatsFlag, customerStatsFlag, newCustomersByMonthFlag);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body14 {\n");

    sb.append("    deviceid: ").append(toIndentedString(deviceid)).append("\n");
    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("    campaignRedemptionStatsFlag: ").append(toIndentedString(campaignRedemptionStatsFlag)).append("\n");
    sb.append("    customerStatsFlag: ").append(toIndentedString(customerStatsFlag)).append("\n");
    sb.append("    newCustomersByMonthFlag: ").append(toIndentedString(newCustomersByMonthFlag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
