/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Body18
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class Body18 {
  @SerializedName("mer_id")
  private String merId = null;

  @SerializedName("customerid")
  private String customerid = null;

  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  @SerializedName("deviceid")
  private String deviceid = null;

  @SerializedName("oldpin")
  private BigDecimal oldpin = null;

  @SerializedName("newpin")
  private BigDecimal newpin = null;

  @SerializedName("callertype")
  private String callertype = null;

  public Body18 merId(String merId) {
    this.merId = merId;
    return this;
  }

   /**
   * Get merId
   * @return merId
  **/
  @Schema(required = true, description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }

  public Body18 customerid(String customerid) {
    this.customerid = customerid;
    return this;
  }

   /**
   * Get customerid
   * @return customerid
  **/
  @Schema(required = true, description = "")
  public String getCustomerid() {
    return customerid;
  }

  public void setCustomerid(String customerid) {
    this.customerid = customerid;
  }

  public Body18 sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
  @Schema(required = true, description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }

  public Body18 deviceid(String deviceid) {
    this.deviceid = deviceid;
    return this;
  }

   /**
   * Get deviceid
   * @return deviceid
  **/
  @Schema(required = true, description = "")
  public String getDeviceid() {
    return deviceid;
  }

  public void setDeviceid(String deviceid) {
    this.deviceid = deviceid;
  }

  public Body18 oldpin(BigDecimal oldpin) {
    this.oldpin = oldpin;
    return this;
  }

   /**
   * Get oldpin
   * @return oldpin
  **/
  @Schema(required = true, description = "")
  public BigDecimal getOldpin() {
    return oldpin;
  }

  public void setOldpin(BigDecimal oldpin) {
    this.oldpin = oldpin;
  }

  public Body18 newpin(BigDecimal newpin) {
    this.newpin = newpin;
    return this;
  }

   /**
   * Get newpin
   * @return newpin
  **/
  @Schema(required = true, description = "")
  public BigDecimal getNewpin() {
    return newpin;
  }

  public void setNewpin(BigDecimal newpin) {
    this.newpin = newpin;
  }

  public Body18 callertype(String callertype) {
    this.callertype = callertype;
    return this;
  }

   /**
   * Get callertype
   * @return callertype
  **/
  @Schema(required = true, description = "")
  public String getCallertype() {
    return callertype;
  }

  public void setCallertype(String callertype) {
    this.callertype = callertype;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body18 body18 = (Body18) o;
    return Objects.equals(this.merId, body18.merId) &&
        Objects.equals(this.customerid, body18.customerid) &&
        Objects.equals(this.sessiontoken, body18.sessiontoken) &&
        Objects.equals(this.deviceid, body18.deviceid) &&
        Objects.equals(this.oldpin, body18.oldpin) &&
        Objects.equals(this.newpin, body18.newpin) &&
        Objects.equals(this.callertype, body18.callertype);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merId, customerid, sessiontoken, deviceid, oldpin, newpin, callertype);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body18 {\n");

    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("    customerid: ").append(toIndentedString(customerid)).append("\n");
    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("    deviceid: ").append(toIndentedString(deviceid)).append("\n");
    sb.append("    oldpin: ").append(toIndentedString(oldpin)).append("\n");
    sb.append("    newpin: ").append(toIndentedString(newpin)).append("\n");
    sb.append("    callertype: ").append(toIndentedString(callertype)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
