/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Body10
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class Body10 {
  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  @SerializedName("mer_id")
  private String merId = null;

  @SerializedName("cust_id")
  private String custId = null;

  @SerializedName("outlet_version")
  private String outletVersion = null;

  @SerializedName("campaign_version")
  private String campaignVersion = null;

  @SerializedName("mer_qr_version")
  private String merQrVersion = null;

  @SerializedName("mer_params_version")
  private String merParamsVersion = null;

  @SerializedName("mer_lov_version")
  private String merLovVersion = null;

  @SerializedName("cust_lov_version")
  private String custLovVersion = null;

  @SerializedName("callertype")
  private String callertype = null;

  public Body10 sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
  @Schema(description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }

  public Body10 merId(String merId) {
    this.merId = merId;
    return this;
  }

   /**
   * Get merId
   * @return merId
  **/
  @Schema(description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }

  public Body10 custId(String custId) {
    this.custId = custId;
    return this;
  }

   /**
   * Get custId
   * @return custId
  **/
  @Schema(description = "")
  public String getCustId() {
    return custId;
  }

  public void setCustId(String custId) {
    this.custId = custId;
  }

  public Body10 outletVersion(String outletVersion) {
    this.outletVersion = outletVersion;
    return this;
  }

   /**
   * Get outletVersion
   * @return outletVersion
  **/
  @Schema(description = "")
  public String getOutletVersion() {
    return outletVersion;
  }

  public void setOutletVersion(String outletVersion) {
    this.outletVersion = outletVersion;
  }

  public Body10 campaignVersion(String campaignVersion) {
    this.campaignVersion = campaignVersion;
    return this;
  }

   /**
   * Get campaignVersion
   * @return campaignVersion
  **/
  @Schema(description = "")
  public String getCampaignVersion() {
    return campaignVersion;
  }

  public void setCampaignVersion(String campaignVersion) {
    this.campaignVersion = campaignVersion;
  }

  public Body10 merQrVersion(String merQrVersion) {
    this.merQrVersion = merQrVersion;
    return this;
  }

   /**
   * Get merQrVersion
   * @return merQrVersion
  **/
  @Schema(description = "")
  public String getMerQrVersion() {
    return merQrVersion;
  }

  public void setMerQrVersion(String merQrVersion) {
    this.merQrVersion = merQrVersion;
  }

  public Body10 merParamsVersion(String merParamsVersion) {
    this.merParamsVersion = merParamsVersion;
    return this;
  }

   /**
   * Get merParamsVersion
   * @return merParamsVersion
  **/
  @Schema(description = "")
  public String getMerParamsVersion() {
    return merParamsVersion;
  }

  public void setMerParamsVersion(String merParamsVersion) {
    this.merParamsVersion = merParamsVersion;
  }

  public Body10 merLovVersion(String merLovVersion) {
    this.merLovVersion = merLovVersion;
    return this;
  }

   /**
   * Get merLovVersion
   * @return merLovVersion
  **/
  @Schema(description = "")
  public String getMerLovVersion() {
    return merLovVersion;
  }

  public void setMerLovVersion(String merLovVersion) {
    this.merLovVersion = merLovVersion;
  }

  public Body10 custLovVersion(String custLovVersion) {
    this.custLovVersion = custLovVersion;
    return this;
  }

   /**
   * Get custLovVersion
   * @return custLovVersion
  **/
  @Schema(description = "")
  public String getCustLovVersion() {
    return custLovVersion;
  }

  public void setCustLovVersion(String custLovVersion) {
    this.custLovVersion = custLovVersion;
  }

  public Body10 callertype(String callertype) {
    this.callertype = callertype;
    return this;
  }

   /**
   * Get callertype
   * @return callertype
  **/
  @Schema(description = "")
  public String getCallertype() {
    return callertype;
  }

  public void setCallertype(String callertype) {
    this.callertype = callertype;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body10 body10 = (Body10) o;
    return Objects.equals(this.sessiontoken, body10.sessiontoken) &&
        Objects.equals(this.merId, body10.merId) &&
        Objects.equals(this.custId, body10.custId) &&
        Objects.equals(this.outletVersion, body10.outletVersion) &&
        Objects.equals(this.campaignVersion, body10.campaignVersion) &&
        Objects.equals(this.merQrVersion, body10.merQrVersion) &&
        Objects.equals(this.merParamsVersion, body10.merParamsVersion) &&
        Objects.equals(this.merLovVersion, body10.merLovVersion) &&
        Objects.equals(this.custLovVersion, body10.custLovVersion) &&
        Objects.equals(this.callertype, body10.callertype);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessiontoken, merId, custId, outletVersion, campaignVersion, merQrVersion, merParamsVersion, merLovVersion, custLovVersion, callertype);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body10 {\n");

    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("    custId: ").append(toIndentedString(custId)).append("\n");
    sb.append("    outletVersion: ").append(toIndentedString(outletVersion)).append("\n");
    sb.append("    campaignVersion: ").append(toIndentedString(campaignVersion)).append("\n");
    sb.append("    merQrVersion: ").append(toIndentedString(merQrVersion)).append("\n");
    sb.append("    merParamsVersion: ").append(toIndentedString(merParamsVersion)).append("\n");
    sb.append("    merLovVersion: ").append(toIndentedString(merLovVersion)).append("\n");
    sb.append("    custLovVersion: ").append(toIndentedString(custLovVersion)).append("\n");
    sb.append("    callertype: ").append(toIndentedString(callertype)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
