/*
 * Corals app
 * Corals openAPI file
 *
 * OpenAPI spec version: 0.0.10
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * CustomerCheckInInfoBody
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-13T14:44:27.493Z")
public class CustomerCheckInInfoBody {
  @SerializedName("curr_geo_lat")
  private String currGeoLat = null;

  @SerializedName("curr_geo_lng")
  private String currGeoLng = null;

  @SerializedName("cust_id")
  private String custId = null;

  @SerializedName("is_check_in")
  private Boolean isCheckIn = null;

  @SerializedName("mer_id")
  private String merId = null;

  @SerializedName("outlet_id")
  private String outletId = null;

  public CustomerCheckInInfoBody currGeoLat(String currGeoLat) {
    this.currGeoLat = currGeoLat;
    return this;
  }

   /**
   * Get currGeoLat
   * @return currGeoLat
  **/
   @Schema(required = true, description = "")
  public String getCurrGeoLat() {
    return currGeoLat;
  }

  public void setCurrGeoLat(String currGeoLat) {
    this.currGeoLat = currGeoLat;
  }

  public CustomerCheckInInfoBody currGeoLng(String currGeoLng) {
    this.currGeoLng = currGeoLng;
    return this;
  }

   /**
   * Get currGeoLng
   * @return currGeoLng
  **/
   @Schema(required = true, description = "")
  public String getCurrGeoLng() {
    return currGeoLng;
  }

  public void setCurrGeoLng(String currGeoLng) {
    this.currGeoLng = currGeoLng;
  }

  public CustomerCheckInInfoBody custId(String custId) {
    this.custId = custId;
    return this;
  }

   /**
   * Get custId
   * @return custId
  **/
   @Schema(required = true, description = "")
  public String getCustId() {
    return custId;
  }

  public void setCustId(String custId) {
    this.custId = custId;
  }

  public CustomerCheckInInfoBody isCheckIn(Boolean isCheckIn) {
    this.isCheckIn = isCheckIn;
    return this;
  }

   /**
   * Get isCheckIn
   * @return isCheckIn
  **/
   @Schema(required = true, description = "")
  public Boolean isIsCheckIn() {
    return isCheckIn;
  }

  public void setIsCheckIn(Boolean isCheckIn) {
    this.isCheckIn = isCheckIn;
  }

  public CustomerCheckInInfoBody merId(String merId) {
    this.merId = merId;
    return this;
  }

   /**
   * Get merId
   * @return merId
  **/
   @Schema(required = true, description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }

  public CustomerCheckInInfoBody outletId(String outletId) {
    this.outletId = outletId;
    return this;
  }

   /**
   * Get outletId
   * @return outletId
  **/
   @Schema(required = true, description = "")
  public String getOutletId() {
    return outletId;
  }

  public void setOutletId(String outletId) {
    this.outletId = outletId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerCheckInInfoBody customerCheckInInfoBody = (CustomerCheckInInfoBody) o;
    return Objects.equals(this.currGeoLat, customerCheckInInfoBody.currGeoLat) &&
        Objects.equals(this.currGeoLng, customerCheckInInfoBody.currGeoLng) &&
        Objects.equals(this.custId, customerCheckInInfoBody.custId) &&
        Objects.equals(this.isCheckIn, customerCheckInInfoBody.isCheckIn) &&
        Objects.equals(this.merId, customerCheckInInfoBody.merId) &&
        Objects.equals(this.outletId, customerCheckInInfoBody.outletId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currGeoLat, currGeoLng, custId, isCheckIn, merId, outletId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerCheckInInfoBody {\n");
    
    sb.append("    currGeoLat: ").append(toIndentedString(currGeoLat)).append("\n");
    sb.append("    currGeoLng: ").append(toIndentedString(currGeoLng)).append("\n");
    sb.append("    custId: ").append(toIndentedString(custId)).append("\n");
    sb.append("    isCheckIn: ").append(toIndentedString(isCheckIn)).append("\n");
    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("    outletId: ").append(toIndentedString(outletId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

