/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * GenerictokengenerateRedeem
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class GenerictokengenerateRedeem {
  @SerializedName("paymentamount")
  private String paymentamount = null;

  public GenerictokengenerateRedeem paymentamount(String paymentamount) {
    this.paymentamount = paymentamount;
    return this;
  }

   /**
   * Get paymentamount
   * @return paymentamount
  **/
  @Schema(description = "")
  public String getPaymentamount() {
    return paymentamount;
  }

  public void setPaymentamount(String paymentamount) {
    this.paymentamount = paymentamount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenerictokengenerateRedeem generictokengenerateRedeem = (GenerictokengenerateRedeem) o;
    return Objects.equals(this.paymentamount, generictokengenerateRedeem.paymentamount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentamount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenerictokengenerateRedeem {\n");

    sb.append("    paymentamount: ").append(toIndentedString(paymentamount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
