/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse2009Outlets
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class InlineResponse2009Outlets {
  @SerializedName("outlet_id")
  private String outletId = null;

  @SerializedName("outlet_name")
  private String outletName = null;

  @SerializedName("outlet_add1")
  private String outletAdd1 = null;

  @SerializedName("outlet_add2")
  private String outletAdd2 = null;

  @SerializedName("outlet_add3")
  private String outletAdd3 = null;

  @SerializedName("post_code")
  private String postCode = null;

  @SerializedName("phone_no")
  private BigDecimal phoneNo = null;

  @SerializedName("geo_lat")
  private String geoLat = null;

  @SerializedName("geo_lon")
  private String geoLon = null;

  public InlineResponse2009Outlets outletId(String outletId) {
    this.outletId = outletId;
    return this;
  }

   /**
   * Get outletId
   * @return outletId
  **/
  @Schema(description = "")
  public String getOutletId() {
    return outletId;
  }

  public void setOutletId(String outletId) {
    this.outletId = outletId;
  }

  public InlineResponse2009Outlets outletName(String outletName) {
    this.outletName = outletName;
    return this;
  }

   /**
   * Get outletName
   * @return outletName
  **/
  @Schema(description = "")
  public String getOutletName() {
    return outletName;
  }

  public void setOutletName(String outletName) {
    this.outletName = outletName;
  }

  public InlineResponse2009Outlets outletAdd1(String outletAdd1) {
    this.outletAdd1 = outletAdd1;
    return this;
  }

   /**
   * Get outletAdd1
   * @return outletAdd1
  **/
  @Schema(description = "")
  public String getOutletAdd1() {
    return outletAdd1;
  }

  public void setOutletAdd1(String outletAdd1) {
    this.outletAdd1 = outletAdd1;
  }

  public InlineResponse2009Outlets outletAdd2(String outletAdd2) {
    this.outletAdd2 = outletAdd2;
    return this;
  }

   /**
   * Get outletAdd2
   * @return outletAdd2
  **/
  @Schema(description = "")
  public String getOutletAdd2() {
    return outletAdd2;
  }

  public void setOutletAdd2(String outletAdd2) {
    this.outletAdd2 = outletAdd2;
  }

  public InlineResponse2009Outlets outletAdd3(String outletAdd3) {
    this.outletAdd3 = outletAdd3;
    return this;
  }

   /**
   * Get outletAdd3
   * @return outletAdd3
  **/
  @Schema(description = "")
  public String getOutletAdd3() {
    return outletAdd3;
  }

  public void setOutletAdd3(String outletAdd3) {
    this.outletAdd3 = outletAdd3;
  }

  public InlineResponse2009Outlets postCode(String postCode) {
    this.postCode = postCode;
    return this;
  }

   /**
   * Get postCode
   * @return postCode
  **/
  @Schema(description = "")
  public String getPostCode() {
    return postCode;
  }

  public void setPostCode(String postCode) {
    this.postCode = postCode;
  }

  public InlineResponse2009Outlets phoneNo(BigDecimal phoneNo) {
    this.phoneNo = phoneNo;
    return this;
  }

   /**
   * Get phoneNo
   * @return phoneNo
  **/
  @Schema(description = "")
  public BigDecimal getPhoneNo() {
    return phoneNo;
  }

  public void setPhoneNo(BigDecimal phoneNo) {
    this.phoneNo = phoneNo;
  }

  public InlineResponse2009Outlets geoLat(String geoLat) {
    this.geoLat = geoLat;
    return this;
  }

   /**
   * Get geoLat
   * @return geoLat
  **/
  @Schema(description = "")
  public String getGeoLat() {
    return geoLat;
  }

  public void setGeoLat(String geoLat) {
    this.geoLat = geoLat;
  }

  public InlineResponse2009Outlets geoLon(String geoLon) {
    this.geoLon = geoLon;
    return this;
  }

   /**
   * Get geoLon
   * @return geoLon
  **/
  @Schema(description = "")
  public String getGeoLon() {
    return geoLon;
  }

  public void setGeoLon(String geoLon) {
    this.geoLon = geoLon;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2009Outlets inlineResponse2009Outlets = (InlineResponse2009Outlets) o;
    return Objects.equals(this.outletId, inlineResponse2009Outlets.outletId) &&
        Objects.equals(this.outletName, inlineResponse2009Outlets.outletName) &&
        Objects.equals(this.outletAdd1, inlineResponse2009Outlets.outletAdd1) &&
        Objects.equals(this.outletAdd2, inlineResponse2009Outlets.outletAdd2) &&
        Objects.equals(this.outletAdd3, inlineResponse2009Outlets.outletAdd3) &&
        Objects.equals(this.postCode, inlineResponse2009Outlets.postCode) &&
        Objects.equals(this.phoneNo, inlineResponse2009Outlets.phoneNo) &&
        Objects.equals(this.geoLat, inlineResponse2009Outlets.geoLat) &&
        Objects.equals(this.geoLon, inlineResponse2009Outlets.geoLon);
  }

  @Override
  public int hashCode() {
    return Objects.hash(outletId, outletName, outletAdd1, outletAdd2, outletAdd3, postCode, phoneNo, geoLat, geoLon);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2009Outlets {\n");

    sb.append("    outletId: ").append(toIndentedString(outletId)).append("\n");
    sb.append("    outletName: ").append(toIndentedString(outletName)).append("\n");
    sb.append("    outletAdd1: ").append(toIndentedString(outletAdd1)).append("\n");
    sb.append("    outletAdd2: ").append(toIndentedString(outletAdd2)).append("\n");
    sb.append("    outletAdd3: ").append(toIndentedString(outletAdd3)).append("\n");
    sb.append("    postCode: ").append(toIndentedString(postCode)).append("\n");
    sb.append("    phoneNo: ").append(toIndentedString(phoneNo)).append("\n");
    sb.append("    geoLat: ").append(toIndentedString(geoLat)).append("\n");
    sb.append("    geoLon: ").append(toIndentedString(geoLon)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
