/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse20012MerredeemlistRedeemGrps
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class InlineResponse20012MerredeemlistRedeemGrps {
  @SerializedName("groupid")
  private String groupid = null;

  @SerializedName("groupname")
  private String groupname = null;

  public InlineResponse20012MerredeemlistRedeemGrps groupid(String groupid) {
    this.groupid = groupid;
    return this;
  }

   /**
   * Get groupid
   * @return groupid
  **/
  @Schema(description = "")
  public String getGroupid() {
    return groupid;
  }

  public void setGroupid(String groupid) {
    this.groupid = groupid;
  }

  public InlineResponse20012MerredeemlistRedeemGrps groupname(String groupname) {
    this.groupname = groupname;
    return this;
  }

   /**
   * Get groupname
   * @return groupname
  **/
  @Schema(description = "")
  public String getGroupname() {
    return groupname;
  }

  public void setGroupname(String groupname) {
    this.groupname = groupname;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20012MerredeemlistRedeemGrps inlineResponse20012MerredeemlistRedeemGrps = (InlineResponse20012MerredeemlistRedeemGrps) o;
    return Objects.equals(this.groupid, inlineResponse20012MerredeemlistRedeemGrps.groupid) &&
        Objects.equals(this.groupname, inlineResponse20012MerredeemlistRedeemGrps.groupname);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupid, groupname);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20012MerredeemlistRedeemGrps {\n");

    sb.append("    groupid: ").append(toIndentedString(groupid)).append("\n");
    sb.append("    groupname: ").append(toIndentedString(groupname)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
