/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse20012Transactions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class InlineResponse20012Transactions {
  @SerializedName("paymentAmt")
  private String paymentAmt = null;

  @SerializedName("walletbalance")
  private String walletbalance = null;

  @SerializedName("customerid")
  private String customerid = null;

  @SerializedName("mobile_no")
  private String mobileNo = null;

  @SerializedName("datetime")
  private String datetime = null;

  @SerializedName("txnrefno")
  private String txnrefno = null;

  @SerializedName("outletid")
  private String outletid = null;

  @SerializedName("transaction_type")
  private String transactionType = null;

  public InlineResponse20012Transactions paymentAmt(String paymentAmt) {
    this.paymentAmt = paymentAmt;
    return this;
  }

   /**
   * Get paymentAmt
   * @return paymentAmt
  **/
  @Schema(description = "")
  public String getPaymentAmt() {
    return paymentAmt;
  }

  public void setPaymentAmt(String paymentAmt) {
    this.paymentAmt = paymentAmt;
  }

  public InlineResponse20012Transactions walletbalance(String walletbalance) {
    this.walletbalance = walletbalance;
    return this;
  }

   /**
   * Get walletbalance
   * @return walletbalance
  **/
  @Schema(description = "")
  public String getWalletbalance() {
    return walletbalance;
  }

  public void setWalletbalance(String walletbalance) {
    this.walletbalance = walletbalance;
  }

  public InlineResponse20012Transactions customerid(String customerid) {
    this.customerid = customerid;
    return this;
  }

   /**
   * Get customerid
   * @return customerid
  **/
  @Schema(description = "")
  public String getCustomerid() {
    return customerid;
  }

  public void setCustomerid(String customerid) {
    this.customerid = customerid;
  }

  public InlineResponse20012Transactions mobileNo(String mobileNo) {
    this.mobileNo = mobileNo;
    return this;
  }

   /**
   * Get mobileNo
   * @return mobileNo
  **/
  @Schema(description = "")
  public String getMobileNo() {
    return mobileNo;
  }

  public void setMobileNo(String mobileNo) {
    this.mobileNo = mobileNo;
  }

  public InlineResponse20012Transactions datetime(String datetime) {
    this.datetime = datetime;
    return this;
  }

   /**
   * Get datetime
   * @return datetime
  **/
  @Schema(description = "")
  public String getDatetime() {
    return datetime;
  }

  public void setDatetime(String datetime) {
    this.datetime = datetime;
  }

  public InlineResponse20012Transactions txnrefno(String txnrefno) {
    this.txnrefno = txnrefno;
    return this;
  }

   /**
   * Get txnrefno
   * @return txnrefno
  **/
  @Schema(description = "")
  public String getTxnrefno() {
    return txnrefno;
  }

  public void setTxnrefno(String txnrefno) {
    this.txnrefno = txnrefno;
  }

  public InlineResponse20012Transactions outletid(String outletid) {
    this.outletid = outletid;
    return this;
  }

   /**
   * Get outletid
   * @return outletid
  **/
  @Schema(description = "")
  public String getOutletid() {
    return outletid;
  }

  public void setOutletid(String outletid) {
    this.outletid = outletid;
  }

  public InlineResponse20012Transactions transactionType(String transactionType) {
    this.transactionType = transactionType;
    return this;
  }

   /**
   * Get transactionType
   * @return transactionType
  **/
  @Schema(description = "")
  public String getTransactionType() {
    return transactionType;
  }

  public void setTransactionType(String transactionType) {
    this.transactionType = transactionType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20012Transactions inlineResponse20012Transactions = (InlineResponse20012Transactions) o;
    return Objects.equals(this.paymentAmt, inlineResponse20012Transactions.paymentAmt) &&
        Objects.equals(this.walletbalance, inlineResponse20012Transactions.walletbalance) &&
        Objects.equals(this.customerid, inlineResponse20012Transactions.customerid) &&
        Objects.equals(this.mobileNo, inlineResponse20012Transactions.mobileNo) &&
        Objects.equals(this.datetime, inlineResponse20012Transactions.datetime) &&
        Objects.equals(this.txnrefno, inlineResponse20012Transactions.txnrefno) &&
        Objects.equals(this.outletid, inlineResponse20012Transactions.outletid) &&
        Objects.equals(this.transactionType, inlineResponse20012Transactions.transactionType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentAmt, walletbalance, customerid, mobileNo, datetime, txnrefno, outletid, transactionType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20012Transactions {\n");

    sb.append("    paymentAmt: ").append(toIndentedString(paymentAmt)).append("\n");
    sb.append("    walletbalance: ").append(toIndentedString(walletbalance)).append("\n");
    sb.append("    customerid: ").append(toIndentedString(customerid)).append("\n");
    sb.append("    mobileNo: ").append(toIndentedString(mobileNo)).append("\n");
    sb.append("    datetime: ").append(toIndentedString(datetime)).append("\n");
    sb.append("    txnrefno: ").append(toIndentedString(txnrefno)).append("\n");
    sb.append("    outletid: ").append(toIndentedString(outletid)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
