/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse20011CampaignRedemptionStats
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class InlineResponse20011CampaignRedemptionStats {
  @SerializedName("campaignid")
  private String campaignid = null;

  @SerializedName("campaign_name")
  private String campaignName = null;

  @SerializedName("topups_today")
  private String topupsToday = null;

  @SerializedName("topups_this_week")
  private String topupsThisWeek = null;

  @SerializedName("topups_this_month")
  private String topupsThisMonth = null;

  @SerializedName("topups_last_month")
  private String topupsLastMonth = null;

  @SerializedName("topups_ytd")
  private String topupsYtd = null;

  public InlineResponse20011CampaignRedemptionStats campaignid(String campaignid) {
    this.campaignid = campaignid;
    return this;
  }

   /**
   * Get campaignid
   * @return campaignid
  **/
  @Schema(description = "")
  public String getCampaignid() {
    return campaignid;
  }

  public void setCampaignid(String campaignid) {
    this.campaignid = campaignid;
  }

  public InlineResponse20011CampaignRedemptionStats campaignName(String campaignName) {
    this.campaignName = campaignName;
    return this;
  }

   /**
   * Get campaignName
   * @return campaignName
  **/
  @Schema(description = "")
  public String getCampaignName() {
    return campaignName;
  }

  public void setCampaignName(String campaignName) {
    this.campaignName = campaignName;
  }

  public InlineResponse20011CampaignRedemptionStats topupsToday(String topupsToday) {
    this.topupsToday = topupsToday;
    return this;
  }

   /**
   * Get topupsToday
   * @return topupsToday
  **/
  @Schema(description = "")
  public String getTopupsToday() {
    return topupsToday;
  }

  public void setTopupsToday(String topupsToday) {
    this.topupsToday = topupsToday;
  }

  public InlineResponse20011CampaignRedemptionStats topupsThisWeek(String topupsThisWeek) {
    this.topupsThisWeek = topupsThisWeek;
    return this;
  }

   /**
   * Get topupsThisWeek
   * @return topupsThisWeek
  **/
  @Schema(description = "")
  public String getTopupsThisWeek() {
    return topupsThisWeek;
  }

  public void setTopupsThisWeek(String topupsThisWeek) {
    this.topupsThisWeek = topupsThisWeek;
  }

  public InlineResponse20011CampaignRedemptionStats topupsThisMonth(String topupsThisMonth) {
    this.topupsThisMonth = topupsThisMonth;
    return this;
  }

   /**
   * Get topupsThisMonth
   * @return topupsThisMonth
  **/
  @Schema(description = "")
  public String getTopupsThisMonth() {
    return topupsThisMonth;
  }

  public void setTopupsThisMonth(String topupsThisMonth) {
    this.topupsThisMonth = topupsThisMonth;
  }

  public InlineResponse20011CampaignRedemptionStats topupsLastMonth(String topupsLastMonth) {
    this.topupsLastMonth = topupsLastMonth;
    return this;
  }

   /**
   * Get topupsLastMonth
   * @return topupsLastMonth
  **/
  @Schema(description = "")
  public String getTopupsLastMonth() {
    return topupsLastMonth;
  }

  public void setTopupsLastMonth(String topupsLastMonth) {
    this.topupsLastMonth = topupsLastMonth;
  }

  public InlineResponse20011CampaignRedemptionStats topupsYtd(String topupsYtd) {
    this.topupsYtd = topupsYtd;
    return this;
  }

   /**
   * Get topupsYtd
   * @return topupsYtd
  **/
  @Schema(description = "")
  public String getTopupsYtd() {
    return topupsYtd;
  }

  public void setTopupsYtd(String topupsYtd) {
    this.topupsYtd = topupsYtd;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20011CampaignRedemptionStats inlineResponse20011CampaignRedemptionStats = (InlineResponse20011CampaignRedemptionStats) o;
    return Objects.equals(this.campaignid, inlineResponse20011CampaignRedemptionStats.campaignid) &&
        Objects.equals(this.campaignName, inlineResponse20011CampaignRedemptionStats.campaignName) &&
        Objects.equals(this.topupsToday, inlineResponse20011CampaignRedemptionStats.topupsToday) &&
        Objects.equals(this.topupsThisWeek, inlineResponse20011CampaignRedemptionStats.topupsThisWeek) &&
        Objects.equals(this.topupsThisMonth, inlineResponse20011CampaignRedemptionStats.topupsThisMonth) &&
        Objects.equals(this.topupsLastMonth, inlineResponse20011CampaignRedemptionStats.topupsLastMonth) &&
        Objects.equals(this.topupsYtd, inlineResponse20011CampaignRedemptionStats.topupsYtd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaignid, campaignName, topupsToday, topupsThisWeek, topupsThisMonth, topupsLastMonth, topupsYtd);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20011CampaignRedemptionStats {\n");

    sb.append("    campaignid: ").append(toIndentedString(campaignid)).append("\n");
    sb.append("    campaignName: ").append(toIndentedString(campaignName)).append("\n");
    sb.append("    topupsToday: ").append(toIndentedString(topupsToday)).append("\n");
    sb.append("    topupsThisWeek: ").append(toIndentedString(topupsThisWeek)).append("\n");
    sb.append("    topupsThisMonth: ").append(toIndentedString(topupsThisMonth)).append("\n");
    sb.append("    topupsLastMonth: ").append(toIndentedString(topupsLastMonth)).append("\n");
    sb.append("    topupsYtd: ").append(toIndentedString(topupsYtd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
