/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse20011TopUpCountByMonth
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class InlineResponse20011TopUpCountByMonth {
  @SerializedName("year")
  private String year = null;

  @SerializedName("month")
  private String month = null;

  @SerializedName("top_up_count")
  private String topUpCount = null;

  @SerializedName("top_up_value")
  private String topUpValue = null;

  @SerializedName("bonus_value")
  private String bonusValue = null;

  public InlineResponse20011TopUpCountByMonth year(String year) {
    this.year = year;
    return this;
  }

   /**
   * Get year
   * @return year
  **/
  @Schema(description = "")
  public String getYear() {
    return year;
  }

  public void setYear(String year) {
    this.year = year;
  }

  public InlineResponse20011TopUpCountByMonth month(String month) {
    this.month = month;
    return this;
  }

   /**
   * Get month
   * @return month
  **/
  @Schema(description = "")
  public String getMonth() {
    return month;
  }

  public void setMonth(String month) {
    this.month = month;
  }

  public InlineResponse20011TopUpCountByMonth topUpCount(String topUpCount) {
    this.topUpCount = topUpCount;
    return this;
  }

   /**
   * Get topUpCount
   * @return topUpCount
  **/
  @Schema(description = "")
  public String getTopUpCount() {
    return topUpCount;
  }

  public void setTopUpCount(String topUpCount) {
    this.topUpCount = topUpCount;
  }

  public InlineResponse20011TopUpCountByMonth topUpValue(String topUpValue) {
    this.topUpValue = topUpValue;
    return this;
  }

   /**
   * Get topUpValue
   * @return topUpValue
  **/
  @Schema(description = "")
  public String getTopUpValue() {
    return topUpValue;
  }

  public void setTopUpValue(String topUpValue) {
    this.topUpValue = topUpValue;
  }

  public InlineResponse20011TopUpCountByMonth bonusValue(String bonusValue) {
    this.bonusValue = bonusValue;
    return this;
  }

   /**
   * Get bonusValue
   * @return bonusValue
  **/
  @Schema(description = "")
  public String getBonusValue() {
    return bonusValue;
  }

  public void setBonusValue(String bonusValue) {
    this.bonusValue = bonusValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20011TopUpCountByMonth inlineResponse20011TopUpCountByMonth = (InlineResponse20011TopUpCountByMonth) o;
    return Objects.equals(this.year, inlineResponse20011TopUpCountByMonth.year) &&
        Objects.equals(this.month, inlineResponse20011TopUpCountByMonth.month) &&
        Objects.equals(this.topUpCount, inlineResponse20011TopUpCountByMonth.topUpCount) &&
        Objects.equals(this.topUpValue, inlineResponse20011TopUpCountByMonth.topUpValue) &&
        Objects.equals(this.bonusValue, inlineResponse20011TopUpCountByMonth.bonusValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(year, month, topUpCount, topUpValue, bonusValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20011TopUpCountByMonth {\n");

    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    topUpCount: ").append(toIndentedString(topUpCount)).append("\n");
    sb.append("    topUpValue: ").append(toIndentedString(topUpValue)).append("\n");
    sb.append("    bonusValue: ").append(toIndentedString(bonusValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
