/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse20012
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class InlineResponse20012 {
  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  @SerializedName("mer_id")
  private String merId = null;

  @SerializedName("transactions")
  private List<InlineResponse20012Transactions> transactions = null;

  @SerializedName("merredeemlist")
  private InlineResponse20012Merredeemlist merredeemlist = null;

  public InlineResponse20012 sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
  @Schema(description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }

  public InlineResponse20012 merId(String merId) {
    this.merId = merId;
    return this;
  }

   /**
   * Get merId
   * @return merId
  **/
  @Schema(description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }

  public InlineResponse20012 transactions(List<InlineResponse20012Transactions> transactions) {
    this.transactions = transactions;
    return this;
  }

  public InlineResponse20012 addTransactionsItem(InlineResponse20012Transactions transactionsItem) {
    if (this.transactions == null) {
      this.transactions = new ArrayList<InlineResponse20012Transactions>();
    }
    this.transactions.add(transactionsItem);
    return this;
  }

   /**
   * Get transactions
   * @return transactions
  **/
  @Schema(description = "")
  public List<InlineResponse20012Transactions> getTransactions() {
    return transactions;
  }

  public void setTransactions(List<InlineResponse20012Transactions> transactions) {
    this.transactions = transactions;
  }

  public InlineResponse20012 merredeemlist(InlineResponse20012Merredeemlist merredeemlist) {
    this.merredeemlist = merredeemlist;
    return this;
  }

   /**
   * Get merredeemlist
   * @return merredeemlist
  **/
  @Schema(description = "")
  public InlineResponse20012Merredeemlist getMerredeemlist() {
    return merredeemlist;
  }

  public void setMerredeemlist(InlineResponse20012Merredeemlist merredeemlist) {
    this.merredeemlist = merredeemlist;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20012 inlineResponse20012 = (InlineResponse20012) o;
    return Objects.equals(this.sessiontoken, inlineResponse20012.sessiontoken) &&
        Objects.equals(this.merId, inlineResponse20012.merId) &&
        Objects.equals(this.transactions, inlineResponse20012.transactions) &&
        Objects.equals(this.merredeemlist, inlineResponse20012.merredeemlist);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessiontoken, merId, transactions, merredeemlist);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20012 {\n");

    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("    merredeemlist: ").append(toIndentedString(merredeemlist)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
