/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse20011NewCustomersByMonth
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class InlineResponse20011NewCustomersByMonth {
  @SerializedName("year")
  private String year = null;

  @SerializedName("month")
  private String month = null;

  @SerializedName("customer_count")
  private String customerCount = null;

  @SerializedName("bonus_stats")
  private Object bonusStats = null;

  public InlineResponse20011NewCustomersByMonth year(String year) {
    this.year = year;
    return this;
  }

   /**
   * Get year
   * @return year
  **/
  @Schema(description = "")
  public String getYear() {
    return year;
  }

  public void setYear(String year) {
    this.year = year;
  }

  public InlineResponse20011NewCustomersByMonth month(String month) {
    this.month = month;
    return this;
  }

   /**
   * Get month
   * @return month
  **/
  @Schema(description = "")
  public String getMonth() {
    return month;
  }

  public void setMonth(String month) {
    this.month = month;
  }

  public InlineResponse20011NewCustomersByMonth customerCount(String customerCount) {
    this.customerCount = customerCount;
    return this;
  }

   /**
   * Get customerCount
   * @return customerCount
  **/
  @Schema(description = "")
  public String getCustomerCount() {
    return customerCount;
  }

  public void setCustomerCount(String customerCount) {
    this.customerCount = customerCount;
  }

  public InlineResponse20011NewCustomersByMonth bonusStats(Object bonusStats) {
    this.bonusStats = bonusStats;
    return this;
  }

   /**
   * Get bonusStats
   * @return bonusStats
  **/
  @Schema(description = "")
  public Object getBonusStats() {
    return bonusStats;
  }

  public void setBonusStats(Object bonusStats) {
    this.bonusStats = bonusStats;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20011NewCustomersByMonth inlineResponse20011NewCustomersByMonth = (InlineResponse20011NewCustomersByMonth) o;
    return Objects.equals(this.year, inlineResponse20011NewCustomersByMonth.year) &&
        Objects.equals(this.month, inlineResponse20011NewCustomersByMonth.month) &&
        Objects.equals(this.customerCount, inlineResponse20011NewCustomersByMonth.customerCount) &&
        Objects.equals(this.bonusStats, inlineResponse20011NewCustomersByMonth.bonusStats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(year, month, customerCount, bonusStats);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20011NewCustomersByMonth {\n");

    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    customerCount: ").append(toIndentedString(customerCount)).append("\n");
    sb.append("    bonusStats: ").append(toIndentedString(bonusStats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
