/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse20013Customersrec
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class InlineResponse20013Customersrec {
  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  @SerializedName("cust_id")
  private String custId = null;

  @SerializedName("cust_mobile")
  private String custMobile = null;

  @SerializedName("cust_join_dt")
  private String custJoinDt = null;

  @SerializedName("cust_wallet_bal")
  private String custWalletBal = null;

  @SerializedName("cust_last_top_up")
  private String custLastTopUp = null;

  @SerializedName("cust_last_visit_dt")
  private String custLastVisitDt = null;

  @SerializedName("cust_wallet_exp_dt")
  private String custWalletExpDt = null;

  @SerializedName("cust_country_code")
  private String custCountryCode = null;

  @SerializedName("cust_name")
  private String custName = null;

  @SerializedName("cust_gender")
  private String custGender = null;

  @SerializedName("cust_notification_id")
  private String custNotificationId = null;

  @SerializedName("cust_cb_points_balance")
  private String custCbPointsBalance = null;

  @SerializedName("cust_cb_points_expdt")
  private String custCbPointsExpdt = null;

  public InlineResponse20013Customersrec sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
  @Schema(description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }

  public InlineResponse20013Customersrec custId(String custId) {
    this.custId = custId;
    return this;
  }

   /**
   * Get custId
   * @return custId
  **/
  @Schema(description = "")
  public String getCustId() {
    return custId;
  }

  public void setCustId(String custId) {
    this.custId = custId;
  }

  public InlineResponse20013Customersrec custMobile(String custMobile) {
    this.custMobile = custMobile;
    return this;
  }

   /**
   * Get custMobile
   * @return custMobile
  **/
  @Schema(description = "")
  public String getCustMobile() {
    return custMobile;
  }

  public void setCustMobile(String custMobile) {
    this.custMobile = custMobile;
  }

  public InlineResponse20013Customersrec custJoinDt(String custJoinDt) {
    this.custJoinDt = custJoinDt;
    return this;
  }

   /**
   * Get custJoinDt
   * @return custJoinDt
  **/
  @Schema(description = "")
  public String getCustJoinDt() {
    return custJoinDt;
  }

  public void setCustJoinDt(String custJoinDt) {
    this.custJoinDt = custJoinDt;
  }

  public InlineResponse20013Customersrec custWalletBal(String custWalletBal) {
    this.custWalletBal = custWalletBal;
    return this;
  }

   /**
   * Get custWalletBal
   * @return custWalletBal
  **/
  @Schema(description = "")
  public String getCustWalletBal() {
    return custWalletBal;
  }

  public void setCustWalletBal(String custWalletBal) {
    this.custWalletBal = custWalletBal;
  }

  public InlineResponse20013Customersrec custLastTopUp(String custLastTopUp) {
    this.custLastTopUp = custLastTopUp;
    return this;
  }

   /**
   * Get custLastTopUp
   * @return custLastTopUp
  **/
  @Schema(description = "")
  public String getCustLastTopUp() {
    return custLastTopUp;
  }

  public void setCustLastTopUp(String custLastTopUp) {
    this.custLastTopUp = custLastTopUp;
  }

  public InlineResponse20013Customersrec custLastVisitDt(String custLastVisitDt) {
    this.custLastVisitDt = custLastVisitDt;
    return this;
  }

   /**
   * Get custLastVisitDt
   * @return custLastVisitDt
  **/
  @Schema(description = "")
  public String getCustLastVisitDt() {
    return custLastVisitDt;
  }

  public void setCustLastVisitDt(String custLastVisitDt) {
    this.custLastVisitDt = custLastVisitDt;
  }

  public InlineResponse20013Customersrec custWalletExpDt(String custWalletExpDt) {
    this.custWalletExpDt = custWalletExpDt;
    return this;
  }

   /**
   * Get custWalletExpDt
   * @return custWalletExpDt
  **/
  @Schema(description = "")
  public String getCustWalletExpDt() {
    return custWalletExpDt;
  }

  public void setCustWalletExpDt(String custWalletExpDt) {
    this.custWalletExpDt = custWalletExpDt;
  }

  public InlineResponse20013Customersrec custCountryCode(String custCountryCode) {
    this.custCountryCode = custCountryCode;
    return this;
  }

   /**
   * Get custCountryCode
   * @return custCountryCode
  **/
  @Schema(description = "")
  public String getCustCountryCode() {
    return custCountryCode;
  }

  public void setCustCountryCode(String custCountryCode) {
    this.custCountryCode = custCountryCode;
  }

  public InlineResponse20013Customersrec custName(String custName) {
    this.custName = custName;
    return this;
  }

   /**
   * Get custName
   * @return custName
  **/
  @Schema(description = "")
  public String getCustName() {
    return custName;
  }

  public void setCustName(String custName) {
    this.custName = custName;
  }

  public InlineResponse20013Customersrec custGender(String custGender) {
    this.custGender = custGender;
    return this;
  }

   /**
   * Get custGender
   * @return custGender
  **/
  @Schema(description = "")
  public String getCustGender() {
    return custGender;
  }

  public void setCustGender(String custGender) {
    this.custGender = custGender;
  }

  public InlineResponse20013Customersrec custNotificationId(String custNotificationId) {
    this.custNotificationId = custNotificationId;
    return this;
  }

   /**
   * Get custNotificationId
   * @return custNotificationId
  **/
  @Schema(description = "")
  public String getCustNotificationId() {
    return custNotificationId;
  }

  public void setCustNotificationId(String custNotificationId) {
    this.custNotificationId = custNotificationId;
  }

  public InlineResponse20013Customersrec custCbPointsBalance(String custCbPointsBalance) {
    this.custCbPointsBalance = custCbPointsBalance;
    return this;
  }

   /**
   * Get custCbPointsBalance
   * @return custCbPointsBalance
  **/
  @Schema(description = "")
  public String getCustCbPointsBalance() {
    return custCbPointsBalance;
  }

  public void setCustCbPointsBalance(String custCbPointsBalance) {
    this.custCbPointsBalance = custCbPointsBalance;
  }

  public InlineResponse20013Customersrec custCbPointsExpdt(String custCbPointsExpdt) {
    this.custCbPointsExpdt = custCbPointsExpdt;
    return this;
  }

   /**
   * Get custCbPointsExpdt
   * @return custCbPointsExpdt
  **/
  @Schema(description = "")
  public String getCustCbPointsExpdt() {
    return custCbPointsExpdt;
  }

  public void setCustCbPointsExpdt(String custCbPointsExpdt) {
    this.custCbPointsExpdt = custCbPointsExpdt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20013Customersrec inlineResponse20013Customersrec = (InlineResponse20013Customersrec) o;
    return Objects.equals(this.sessiontoken, inlineResponse20013Customersrec.sessiontoken) &&
        Objects.equals(this.custId, inlineResponse20013Customersrec.custId) &&
        Objects.equals(this.custMobile, inlineResponse20013Customersrec.custMobile) &&
        Objects.equals(this.custJoinDt, inlineResponse20013Customersrec.custJoinDt) &&
        Objects.equals(this.custWalletBal, inlineResponse20013Customersrec.custWalletBal) &&
        Objects.equals(this.custLastTopUp, inlineResponse20013Customersrec.custLastTopUp) &&
        Objects.equals(this.custLastVisitDt, inlineResponse20013Customersrec.custLastVisitDt) &&
        Objects.equals(this.custWalletExpDt, inlineResponse20013Customersrec.custWalletExpDt) &&
        Objects.equals(this.custCountryCode, inlineResponse20013Customersrec.custCountryCode) &&
        Objects.equals(this.custName, inlineResponse20013Customersrec.custName) &&
        Objects.equals(this.custGender, inlineResponse20013Customersrec.custGender) &&
        Objects.equals(this.custNotificationId, inlineResponse20013Customersrec.custNotificationId) &&
        Objects.equals(this.custCbPointsBalance, inlineResponse20013Customersrec.custCbPointsBalance) &&
        Objects.equals(this.custCbPointsExpdt, inlineResponse20013Customersrec.custCbPointsExpdt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessiontoken, custId, custMobile, custJoinDt, custWalletBal, custLastTopUp, custLastVisitDt, custWalletExpDt, custCountryCode, custName, custGender, custNotificationId, custCbPointsBalance, custCbPointsExpdt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20013Customersrec {\n");

    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("    custId: ").append(toIndentedString(custId)).append("\n");
    sb.append("    custMobile: ").append(toIndentedString(custMobile)).append("\n");
    sb.append("    custJoinDt: ").append(toIndentedString(custJoinDt)).append("\n");
    sb.append("    custWalletBal: ").append(toIndentedString(custWalletBal)).append("\n");
    sb.append("    custLastTopUp: ").append(toIndentedString(custLastTopUp)).append("\n");
    sb.append("    custLastVisitDt: ").append(toIndentedString(custLastVisitDt)).append("\n");
    sb.append("    custWalletExpDt: ").append(toIndentedString(custWalletExpDt)).append("\n");
    sb.append("    custCountryCode: ").append(toIndentedString(custCountryCode)).append("\n");
    sb.append("    custName: ").append(toIndentedString(custName)).append("\n");
    sb.append("    custGender: ").append(toIndentedString(custGender)).append("\n");
    sb.append("    custNotificationId: ").append(toIndentedString(custNotificationId)).append("\n");
    sb.append("    custCbPointsBalance: ").append(toIndentedString(custCbPointsBalance)).append("\n");
    sb.append("    custCbPointsExpdt: ").append(toIndentedString(custCbPointsExpdt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
