/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse2007
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class InlineResponse2007 {
  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  @SerializedName("wallet_bal")
  private String walletBal = null;

  @SerializedName("txn_ref_no")
  private String txnRefNo = null;

  @SerializedName("wallet_expriry_dt")
  private String walletExpriryDt = null;

  @SerializedName("request_result")
  private Boolean requestResult = null;

  public InlineResponse2007 sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
  @Schema(description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }

  public InlineResponse2007 walletBal(String walletBal) {
    this.walletBal = walletBal;
    return this;
  }

   /**
   * tbl_cust_txn_ledger. Updated new balance
   * @return walletBal
  **/
  @Schema(description = "tbl_cust_txn_ledger. Updated new balance")
  public String getWalletBal() {
    return walletBal;
  }

  public void setWalletBal(String walletBal) {
    this.walletBal = walletBal;
  }

  public InlineResponse2007 txnRefNo(String txnRefNo) {
    this.txnRefNo = txnRefNo;
    return this;
  }

   /**
   * tbl_cust_txn_ledger
   * @return txnRefNo
  **/
  @Schema(description = "tbl_cust_txn_ledger")
  public String getTxnRefNo() {
    return txnRefNo;
  }

  public void setTxnRefNo(String txnRefNo) {
    this.txnRefNo = txnRefNo;
  }

  public InlineResponse2007 walletExpriryDt(String walletExpriryDt) {
    this.walletExpriryDt = walletExpriryDt;
    return this;
  }

   /**
   * Get walletExpriryDt
   * @return walletExpriryDt
  **/
  @Schema(description = "")
  public String getWalletExpriryDt() {
    return walletExpriryDt;
  }

  public void setWalletExpriryDt(String walletExpriryDt) {
    this.walletExpriryDt = walletExpriryDt;
  }

  public InlineResponse2007 requestResult(Boolean requestResult) {
    this.requestResult = requestResult;
    return this;
  }

   /**
   * send true if request is fullfilled
   * @return requestResult
  **/
  @Schema(description = "send true if request is fullfilled")
  public Boolean isRequestResult() {
    return requestResult;
  }

  public void setRequestResult(Boolean requestResult) {
    this.requestResult = requestResult;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2007 inlineResponse2007 = (InlineResponse2007) o;
    return Objects.equals(this.sessiontoken, inlineResponse2007.sessiontoken) &&
        Objects.equals(this.walletBal, inlineResponse2007.walletBal) &&
        Objects.equals(this.txnRefNo, inlineResponse2007.txnRefNo) &&
        Objects.equals(this.walletExpriryDt, inlineResponse2007.walletExpriryDt) &&
        Objects.equals(this.requestResult, inlineResponse2007.requestResult);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessiontoken, walletBal, txnRefNo, walletExpriryDt, requestResult);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2007 {\n");

    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("    walletBal: ").append(toIndentedString(walletBal)).append("\n");
    sb.append("    txnRefNo: ").append(toIndentedString(txnRefNo)).append("\n");
    sb.append("    walletExpriryDt: ").append(toIndentedString(walletExpriryDt)).append("\n");
    sb.append("    requestResult: ").append(toIndentedString(requestResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
