/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse2004
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class InlineResponse2004 {
  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  @SerializedName("nick_name")
  private String nickName = null;

  @SerializedName("cust_id")
  private String custId = null;

  @SerializedName("member_merchants")
  private List<InlineResponse2004MemberMerchants> memberMerchants = null;

  public InlineResponse2004 sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
  @Schema(description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }

  public InlineResponse2004 nickName(String nickName) {
    this.nickName = nickName;
    return this;
  }

   /**
   * Get nickName
   * @return nickName
  **/
  @Schema(description = "")
  public String getNickName() {
    return nickName;
  }

  public void setNickName(String nickName) {
    this.nickName = nickName;
  }

  public InlineResponse2004 custId(String custId) {
    this.custId = custId;
    return this;
  }

   /**
   * Get custId
   * @return custId
  **/
  @Schema(description = "")
  public String getCustId() {
    return custId;
  }

  public void setCustId(String custId) {
    this.custId = custId;
  }

  public InlineResponse2004 memberMerchants(List<InlineResponse2004MemberMerchants> memberMerchants) {
    this.memberMerchants = memberMerchants;
    return this;
  }

  public InlineResponse2004 addMemberMerchantsItem(InlineResponse2004MemberMerchants memberMerchantsItem) {
    if (this.memberMerchants == null) {
      this.memberMerchants = new ArrayList<InlineResponse2004MemberMerchants>();
    }
    this.memberMerchants.add(memberMerchantsItem);
    return this;
  }

   /**
   * Get memberMerchants
   * @return memberMerchants
  **/
  @Schema(description = "")
  public List<InlineResponse2004MemberMerchants> getMemberMerchants() {
    return memberMerchants;
  }

  public void setMemberMerchants(List<InlineResponse2004MemberMerchants> memberMerchants) {
    this.memberMerchants = memberMerchants;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2004 inlineResponse2004 = (InlineResponse2004) o;
    return Objects.equals(this.sessiontoken, inlineResponse2004.sessiontoken) &&
        Objects.equals(this.nickName, inlineResponse2004.nickName) &&
        Objects.equals(this.custId, inlineResponse2004.custId) &&
        Objects.equals(this.memberMerchants, inlineResponse2004.memberMerchants);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessiontoken, nickName, custId, memberMerchants);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2004 {\n");

    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("    nickName: ").append(toIndentedString(nickName)).append("\n");
    sb.append("    custId: ").append(toIndentedString(custId)).append("\n");
    sb.append("    memberMerchants: ").append(toIndentedString(memberMerchants)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
