/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse20013
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class InlineResponse20013 {
  @SerializedName("Customersrec")
  private List<InlineResponse20013Customersrec> customersrec = null;

  public InlineResponse20013 customersrec(List<InlineResponse20013Customersrec> customersrec) {
    this.customersrec = customersrec;
    return this;
  }

  public InlineResponse20013 addCustomersrecItem(InlineResponse20013Customersrec customersrecItem) {
    if (this.customersrec == null) {
      this.customersrec = new ArrayList<InlineResponse20013Customersrec>();
    }
    this.customersrec.add(customersrecItem);
    return this;
  }

   /**
   * Get customersrec
   * @return customersrec
  **/
  @Schema(description = "")
  public List<InlineResponse20013Customersrec> getCustomersrec() {
    return customersrec;
  }

  public void setCustomersrec(List<InlineResponse20013Customersrec> customersrec) {
    this.customersrec = customersrec;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20013 inlineResponse20013 = (InlineResponse20013) o;
    return Objects.equals(this.customersrec, inlineResponse20013.customersrec);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customersrec);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20013 {\n");

    sb.append("    customersrec: ").append(toIndentedString(customersrec)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
