/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse20011CustomerStats
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class InlineResponse20011CustomerStats {
  @SerializedName("customers_transacted_today")
  private String customersTransactedToday = null;

  @SerializedName("customer_transacted_by_month")
  private List<InlineResponse20011CustomerTransactedByMonth> customerTransactedByMonth = null;

  public InlineResponse20011CustomerStats customersTransactedToday(String customersTransactedToday) {
    this.customersTransactedToday = customersTransactedToday;
    return this;
  }

   /**
   * Get customersTransactedToday
   * @return customersTransactedToday
  **/
  @Schema(description = "")
  public String getCustomersTransactedToday() {
    return customersTransactedToday;
  }

  public void setCustomersTransactedToday(String customersTransactedToday) {
    this.customersTransactedToday = customersTransactedToday;
  }

  public InlineResponse20011CustomerStats customerTransactedByMonth(List<InlineResponse20011CustomerTransactedByMonth> customerTransactedByMonth) {
    this.customerTransactedByMonth = customerTransactedByMonth;
    return this;
  }

  public InlineResponse20011CustomerStats addCustomerTransactedByMonthItem(InlineResponse20011CustomerTransactedByMonth customerTransactedByMonthItem) {
    if (this.customerTransactedByMonth == null) {
      this.customerTransactedByMonth = new ArrayList<InlineResponse20011CustomerTransactedByMonth>();
    }
    this.customerTransactedByMonth.add(customerTransactedByMonthItem);
    return this;
  }

   /**
   * Get customerTransactedByMonth
   * @return customerTransactedByMonth
  **/
  @Schema(description = "")
  public List<InlineResponse20011CustomerTransactedByMonth> getCustomerTransactedByMonth() {
    return customerTransactedByMonth;
  }

  public void setCustomerTransactedByMonth(List<InlineResponse20011CustomerTransactedByMonth> customerTransactedByMonth) {
    this.customerTransactedByMonth = customerTransactedByMonth;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20011CustomerStats inlineResponse20011CustomerStats = (InlineResponse20011CustomerStats) o;
    return Objects.equals(this.customersTransactedToday, inlineResponse20011CustomerStats.customersTransactedToday) &&
        Objects.equals(this.customerTransactedByMonth, inlineResponse20011CustomerStats.customerTransactedByMonth);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customersTransactedToday, customerTransactedByMonth);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20011CustomerStats {\n");

    sb.append("    customersTransactedToday: ").append(toIndentedString(customersTransactedToday)).append("\n");
    sb.append("    customerTransactedByMonth: ").append(toIndentedString(customerTransactedByMonth)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
