/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse20012MerredeemlistRedemptionList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class InlineResponse20012MerredeemlistRedemptionList {
  @SerializedName("mer_cb_redeem_id")
  private String merCbRedeemId = null;

  @SerializedName("redeem_title")
  private String redeemTitle = null;

  @SerializedName("redeem_description")
  private String redeemDescription = null;

  @SerializedName("redeem_points")
  private String redeemPoints = null;

  @SerializedName("redeem_type")
  private String redeemType = null;

  @SerializedName("redeem_deposit_amt")
  private String redeemDepositAmt = null;

  @SerializedName("redeem_activedt")
  private String redeemActivedt = null;

  @SerializedName("redeem_expdt")
  private String redeemExpdt = null;

  @SerializedName("redeem_acttime")
  private String redeemActtime = null;

  @SerializedName("redeem_endtime")
  private String redeemEndtime = null;

  @SerializedName("redeem_grps")
  private List<InlineResponse20012MerredeemlistRedeemGrps> redeemGrps = null;

  public InlineResponse20012MerredeemlistRedemptionList merCbRedeemId(String merCbRedeemId) {
    this.merCbRedeemId = merCbRedeemId;
    return this;
  }

   /**
   * Get merCbRedeemId
   * @return merCbRedeemId
  **/
  @Schema(description = "")
  public String getMerCbRedeemId() {
    return merCbRedeemId;
  }

  public void setMerCbRedeemId(String merCbRedeemId) {
    this.merCbRedeemId = merCbRedeemId;
  }

  public InlineResponse20012MerredeemlistRedemptionList redeemTitle(String redeemTitle) {
    this.redeemTitle = redeemTitle;
    return this;
  }

   /**
   * Get redeemTitle
   * @return redeemTitle
  **/
  @Schema(description = "")
  public String getRedeemTitle() {
    return redeemTitle;
  }

  public void setRedeemTitle(String redeemTitle) {
    this.redeemTitle = redeemTitle;
  }

  public InlineResponse20012MerredeemlistRedemptionList redeemDescription(String redeemDescription) {
    this.redeemDescription = redeemDescription;
    return this;
  }

   /**
   * Get redeemDescription
   * @return redeemDescription
  **/
  @Schema(description = "")
  public String getRedeemDescription() {
    return redeemDescription;
  }

  public void setRedeemDescription(String redeemDescription) {
    this.redeemDescription = redeemDescription;
  }

  public InlineResponse20012MerredeemlistRedemptionList redeemPoints(String redeemPoints) {
    this.redeemPoints = redeemPoints;
    return this;
  }

   /**
   * Get redeemPoints
   * @return redeemPoints
  **/
  @Schema(description = "")
  public String getRedeemPoints() {
    return redeemPoints;
  }

  public void setRedeemPoints(String redeemPoints) {
    this.redeemPoints = redeemPoints;
  }

  public InlineResponse20012MerredeemlistRedemptionList redeemType(String redeemType) {
    this.redeemType = redeemType;
    return this;
  }

   /**
   * Get redeemType
   * @return redeemType
  **/
  @Schema(description = "")
  public String getRedeemType() {
    return redeemType;
  }

  public void setRedeemType(String redeemType) {
    this.redeemType = redeemType;
  }

  public InlineResponse20012MerredeemlistRedemptionList redeemDepositAmt(String redeemDepositAmt) {
    this.redeemDepositAmt = redeemDepositAmt;
    return this;
  }

   /**
   * Get redeemDepositAmt
   * @return redeemDepositAmt
  **/
  @Schema(description = "")
  public String getRedeemDepositAmt() {
    return redeemDepositAmt;
  }

  public void setRedeemDepositAmt(String redeemDepositAmt) {
    this.redeemDepositAmt = redeemDepositAmt;
  }

  public InlineResponse20012MerredeemlistRedemptionList redeemActivedt(String redeemActivedt) {
    this.redeemActivedt = redeemActivedt;
    return this;
  }

   /**
   * Get redeemActivedt
   * @return redeemActivedt
  **/
  @Schema(description = "")
  public String getRedeemActivedt() {
    return redeemActivedt;
  }

  public void setRedeemActivedt(String redeemActivedt) {
    this.redeemActivedt = redeemActivedt;
  }

  public InlineResponse20012MerredeemlistRedemptionList redeemExpdt(String redeemExpdt) {
    this.redeemExpdt = redeemExpdt;
    return this;
  }

   /**
   * Get redeemExpdt
   * @return redeemExpdt
  **/
  @Schema(description = "")
  public String getRedeemExpdt() {
    return redeemExpdt;
  }

  public void setRedeemExpdt(String redeemExpdt) {
    this.redeemExpdt = redeemExpdt;
  }

  public InlineResponse20012MerredeemlistRedemptionList redeemActtime(String redeemActtime) {
    this.redeemActtime = redeemActtime;
    return this;
  }

   /**
   * Get redeemActtime
   * @return redeemActtime
  **/
  @Schema(description = "")
  public String getRedeemActtime() {
    return redeemActtime;
  }

  public void setRedeemActtime(String redeemActtime) {
    this.redeemActtime = redeemActtime;
  }

  public InlineResponse20012MerredeemlistRedemptionList redeemEndtime(String redeemEndtime) {
    this.redeemEndtime = redeemEndtime;
    return this;
  }

   /**
   * Get redeemEndtime
   * @return redeemEndtime
  **/
  @Schema(description = "")
  public String getRedeemEndtime() {
    return redeemEndtime;
  }

  public void setRedeemEndtime(String redeemEndtime) {
    this.redeemEndtime = redeemEndtime;
  }

  public InlineResponse20012MerredeemlistRedemptionList redeemGrps(List<InlineResponse20012MerredeemlistRedeemGrps> redeemGrps) {
    this.redeemGrps = redeemGrps;
    return this;
  }

  public InlineResponse20012MerredeemlistRedemptionList addRedeemGrpsItem(InlineResponse20012MerredeemlistRedeemGrps redeemGrpsItem) {
    if (this.redeemGrps == null) {
      this.redeemGrps = new ArrayList<InlineResponse20012MerredeemlistRedeemGrps>();
    }
    this.redeemGrps.add(redeemGrpsItem);
    return this;
  }

   /**
   * Get redeemGrps
   * @return redeemGrps
  **/
  @Schema(description = "")
  public List<InlineResponse20012MerredeemlistRedeemGrps> getRedeemGrps() {
    return redeemGrps;
  }

  public void setRedeemGrps(List<InlineResponse20012MerredeemlistRedeemGrps> redeemGrps) {
    this.redeemGrps = redeemGrps;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20012MerredeemlistRedemptionList inlineResponse20012MerredeemlistRedemptionList = (InlineResponse20012MerredeemlistRedemptionList) o;
    return Objects.equals(this.merCbRedeemId, inlineResponse20012MerredeemlistRedemptionList.merCbRedeemId) &&
        Objects.equals(this.redeemTitle, inlineResponse20012MerredeemlistRedemptionList.redeemTitle) &&
        Objects.equals(this.redeemDescription, inlineResponse20012MerredeemlistRedemptionList.redeemDescription) &&
        Objects.equals(this.redeemPoints, inlineResponse20012MerredeemlistRedemptionList.redeemPoints) &&
        Objects.equals(this.redeemType, inlineResponse20012MerredeemlistRedemptionList.redeemType) &&
        Objects.equals(this.redeemDepositAmt, inlineResponse20012MerredeemlistRedemptionList.redeemDepositAmt) &&
        Objects.equals(this.redeemActivedt, inlineResponse20012MerredeemlistRedemptionList.redeemActivedt) &&
        Objects.equals(this.redeemExpdt, inlineResponse20012MerredeemlistRedemptionList.redeemExpdt) &&
        Objects.equals(this.redeemActtime, inlineResponse20012MerredeemlistRedemptionList.redeemActtime) &&
        Objects.equals(this.redeemEndtime, inlineResponse20012MerredeemlistRedemptionList.redeemEndtime) &&
        Objects.equals(this.redeemGrps, inlineResponse20012MerredeemlistRedemptionList.redeemGrps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merCbRedeemId, redeemTitle, redeemDescription, redeemPoints, redeemType, redeemDepositAmt, redeemActivedt, redeemExpdt, redeemActtime, redeemEndtime, redeemGrps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20012MerredeemlistRedemptionList {\n");

    sb.append("    merCbRedeemId: ").append(toIndentedString(merCbRedeemId)).append("\n");
    sb.append("    redeemTitle: ").append(toIndentedString(redeemTitle)).append("\n");
    sb.append("    redeemDescription: ").append(toIndentedString(redeemDescription)).append("\n");
    sb.append("    redeemPoints: ").append(toIndentedString(redeemPoints)).append("\n");
    sb.append("    redeemType: ").append(toIndentedString(redeemType)).append("\n");
    sb.append("    redeemDepositAmt: ").append(toIndentedString(redeemDepositAmt)).append("\n");
    sb.append("    redeemActivedt: ").append(toIndentedString(redeemActivedt)).append("\n");
    sb.append("    redeemExpdt: ").append(toIndentedString(redeemExpdt)).append("\n");
    sb.append("    redeemActtime: ").append(toIndentedString(redeemActtime)).append("\n");
    sb.append("    redeemEndtime: ").append(toIndentedString(redeemEndtime)).append("\n");
    sb.append("    redeemGrps: ").append(toIndentedString(redeemGrps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
