/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse20016
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class InlineResponse20016 {
  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  @SerializedName("redeem_type")
  private String redeemType = null;

  @SerializedName("redeem_title")
  private String redeemTitle = null;

  @SerializedName("redeem_depositamt")
  private String redeemDepositamt = null;

  @SerializedName("points_new_balance")
  private String pointsNewBalance = null;

  @SerializedName("points_expiry_dt")
  private String pointsExpiryDt = null;

  @SerializedName("wallet_balance")
  private String walletBalance = null;

  @SerializedName("wallet_currency")
  private String walletCurrency = null;

  @SerializedName("txn-no")
  private String txnNo = null;

  public InlineResponse20016 sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
  @Schema(description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }

  public InlineResponse20016 redeemType(String redeemType) {
    this.redeemType = redeemType;
    return this;
  }

   /**
   * Get redeemType
   * @return redeemType
  **/
  @Schema(description = "")
  public String getRedeemType() {
    return redeemType;
  }

  public void setRedeemType(String redeemType) {
    this.redeemType = redeemType;
  }

  public InlineResponse20016 redeemTitle(String redeemTitle) {
    this.redeemTitle = redeemTitle;
    return this;
  }

   /**
   * Get redeemTitle
   * @return redeemTitle
  **/
  @Schema(description = "")
  public String getRedeemTitle() {
    return redeemTitle;
  }

  public void setRedeemTitle(String redeemTitle) {
    this.redeemTitle = redeemTitle;
  }

  public InlineResponse20016 redeemDepositamt(String redeemDepositamt) {
    this.redeemDepositamt = redeemDepositamt;
    return this;
  }

   /**
   * Get redeemDepositamt
   * @return redeemDepositamt
  **/
  @Schema(description = "")
  public String getRedeemDepositamt() {
    return redeemDepositamt;
  }

  public void setRedeemDepositamt(String redeemDepositamt) {
    this.redeemDepositamt = redeemDepositamt;
  }

  public InlineResponse20016 pointsNewBalance(String pointsNewBalance) {
    this.pointsNewBalance = pointsNewBalance;
    return this;
  }

   /**
   * Get pointsNewBalance
   * @return pointsNewBalance
  **/
  @Schema(description = "")
  public String getPointsNewBalance() {
    return pointsNewBalance;
  }

  public void setPointsNewBalance(String pointsNewBalance) {
    this.pointsNewBalance = pointsNewBalance;
  }

  public InlineResponse20016 pointsExpiryDt(String pointsExpiryDt) {
    this.pointsExpiryDt = pointsExpiryDt;
    return this;
  }

   /**
   * Get pointsExpiryDt
   * @return pointsExpiryDt
  **/
  @Schema(description = "")
  public String getPointsExpiryDt() {
    return pointsExpiryDt;
  }

  public void setPointsExpiryDt(String pointsExpiryDt) {
    this.pointsExpiryDt = pointsExpiryDt;
  }

  public InlineResponse20016 walletBalance(String walletBalance) {
    this.walletBalance = walletBalance;
    return this;
  }

   /**
   * Get walletBalance
   * @return walletBalance
  **/
  @Schema(description = "")
  public String getWalletBalance() {
    return walletBalance;
  }

  public void setWalletBalance(String walletBalance) {
    this.walletBalance = walletBalance;
  }

  public InlineResponse20016 walletCurrency(String walletCurrency) {
    this.walletCurrency = walletCurrency;
    return this;
  }

   /**
   * Get walletCurrency
   * @return walletCurrency
  **/
  @Schema(description = "")
  public String getWalletCurrency() {
    return walletCurrency;
  }

  public void setWalletCurrency(String walletCurrency) {
    this.walletCurrency = walletCurrency;
  }

  public InlineResponse20016 txnNo(String txnNo) {
    this.txnNo = txnNo;
    return this;
  }

   /**
   * Get txnNo
   * @return txnNo
  **/
  @Schema(description = "")
  public String getTxnNo() {
    return txnNo;
  }

  public void setTxnNo(String txnNo) {
    this.txnNo = txnNo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20016 inlineResponse20016 = (InlineResponse20016) o;
    return Objects.equals(this.sessiontoken, inlineResponse20016.sessiontoken) &&
        Objects.equals(this.redeemType, inlineResponse20016.redeemType) &&
        Objects.equals(this.redeemTitle, inlineResponse20016.redeemTitle) &&
        Objects.equals(this.redeemDepositamt, inlineResponse20016.redeemDepositamt) &&
        Objects.equals(this.pointsNewBalance, inlineResponse20016.pointsNewBalance) &&
        Objects.equals(this.pointsExpiryDt, inlineResponse20016.pointsExpiryDt) &&
        Objects.equals(this.walletBalance, inlineResponse20016.walletBalance) &&
        Objects.equals(this.walletCurrency, inlineResponse20016.walletCurrency) &&
        Objects.equals(this.txnNo, inlineResponse20016.txnNo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessiontoken, redeemType, redeemTitle, redeemDepositamt, pointsNewBalance, pointsExpiryDt, walletBalance, walletCurrency, txnNo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20016 {\n");

    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("    redeemType: ").append(toIndentedString(redeemType)).append("\n");
    sb.append("    redeemTitle: ").append(toIndentedString(redeemTitle)).append("\n");
    sb.append("    redeemDepositamt: ").append(toIndentedString(redeemDepositamt)).append("\n");
    sb.append("    pointsNewBalance: ").append(toIndentedString(pointsNewBalance)).append("\n");
    sb.append("    pointsExpiryDt: ").append(toIndentedString(pointsExpiryDt)).append("\n");
    sb.append("    walletBalance: ").append(toIndentedString(walletBalance)).append("\n");
    sb.append("    walletCurrency: ").append(toIndentedString(walletCurrency)).append("\n");
    sb.append("    txnNo: ").append(toIndentedString(txnNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
