/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse20011
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class InlineResponse20011 {
  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  @SerializedName("mer_id")
  private String merId = null;

  @SerializedName("wallet_balance")
  private String walletBalance = null;

  @SerializedName("total_customers")
  private String totalCustomers = null;

  @SerializedName("deposit_spend_ratio")
  private String depositSpendRatio = null;

  @SerializedName("campaign_redemption_stats")
  private List<InlineResponse20011CampaignRedemptionStats> campaignRedemptionStats = null;

  @SerializedName("customer_stats")
  private List<InlineResponse20011CustomerStats> customerStats = null;

  @SerializedName("new_customers_by_month")
  private List<InlineResponse20011NewCustomersByMonth> newCustomersByMonth = null;

  @SerializedName("campaign_performance")
  private List<InlineResponse20011CampaignPerformance> campaignPerformance = null;

  public InlineResponse20011 sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
  @Schema(description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }

  public InlineResponse20011 merId(String merId) {
    this.merId = merId;
    return this;
  }

   /**
   * Get merId
   * @return merId
  **/
  @Schema(description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }

  public InlineResponse20011 walletBalance(String walletBalance) {
    this.walletBalance = walletBalance;
    return this;
  }

   /**
   * Get walletBalance
   * @return walletBalance
  **/
  @Schema(description = "")
  public String getWalletBalance() {
    return walletBalance;
  }

  public void setWalletBalance(String walletBalance) {
    this.walletBalance = walletBalance;
  }

  public InlineResponse20011 totalCustomers(String totalCustomers) {
    this.totalCustomers = totalCustomers;
    return this;
  }

   /**
   * Get totalCustomers
   * @return totalCustomers
  **/
  @Schema(description = "")
  public String getTotalCustomers() {
    return totalCustomers;
  }

  public void setTotalCustomers(String totalCustomers) {
    this.totalCustomers = totalCustomers;
  }

  public InlineResponse20011 depositSpendRatio(String depositSpendRatio) {
    this.depositSpendRatio = depositSpendRatio;
    return this;
  }

   /**
   * Get depositSpendRatio
   * @return depositSpendRatio
  **/
  @Schema(description = "")
  public String getDepositSpendRatio() {
    return depositSpendRatio;
  }

  public void setDepositSpendRatio(String depositSpendRatio) {
    this.depositSpendRatio = depositSpendRatio;
  }

  public InlineResponse20011 campaignRedemptionStats(List<InlineResponse20011CampaignRedemptionStats> campaignRedemptionStats) {
    this.campaignRedemptionStats = campaignRedemptionStats;
    return this;
  }

  public InlineResponse20011 addCampaignRedemptionStatsItem(InlineResponse20011CampaignRedemptionStats campaignRedemptionStatsItem) {
    if (this.campaignRedemptionStats == null) {
      this.campaignRedemptionStats = new ArrayList<InlineResponse20011CampaignRedemptionStats>();
    }
    this.campaignRedemptionStats.add(campaignRedemptionStatsItem);
    return this;
  }

   /**
   * Get campaignRedemptionStats
   * @return campaignRedemptionStats
  **/
  @Schema(description = "")
  public List<InlineResponse20011CampaignRedemptionStats> getCampaignRedemptionStats() {
    return campaignRedemptionStats;
  }

  public void setCampaignRedemptionStats(List<InlineResponse20011CampaignRedemptionStats> campaignRedemptionStats) {
    this.campaignRedemptionStats = campaignRedemptionStats;
  }

  public InlineResponse20011 customerStats(List<InlineResponse20011CustomerStats> customerStats) {
    this.customerStats = customerStats;
    return this;
  }

  public InlineResponse20011 addCustomerStatsItem(InlineResponse20011CustomerStats customerStatsItem) {
    if (this.customerStats == null) {
      this.customerStats = new ArrayList<InlineResponse20011CustomerStats>();
    }
    this.customerStats.add(customerStatsItem);
    return this;
  }

   /**
   * Get customerStats
   * @return customerStats
  **/
  @Schema(description = "")
  public List<InlineResponse20011CustomerStats> getCustomerStats() {
    return customerStats;
  }

  public void setCustomerStats(List<InlineResponse20011CustomerStats> customerStats) {
    this.customerStats = customerStats;
  }

  public InlineResponse20011 newCustomersByMonth(List<InlineResponse20011NewCustomersByMonth> newCustomersByMonth) {
    this.newCustomersByMonth = newCustomersByMonth;
    return this;
  }

  public InlineResponse20011 addNewCustomersByMonthItem(InlineResponse20011NewCustomersByMonth newCustomersByMonthItem) {
    if (this.newCustomersByMonth == null) {
      this.newCustomersByMonth = new ArrayList<InlineResponse20011NewCustomersByMonth>();
    }
    this.newCustomersByMonth.add(newCustomersByMonthItem);
    return this;
  }

   /**
   * Get newCustomersByMonth
   * @return newCustomersByMonth
  **/
  @Schema(description = "")
  public List<InlineResponse20011NewCustomersByMonth> getNewCustomersByMonth() {
    return newCustomersByMonth;
  }

  public void setNewCustomersByMonth(List<InlineResponse20011NewCustomersByMonth> newCustomersByMonth) {
    this.newCustomersByMonth = newCustomersByMonth;
  }

  public InlineResponse20011 campaignPerformance(List<InlineResponse20011CampaignPerformance> campaignPerformance) {
    this.campaignPerformance = campaignPerformance;
    return this;
  }

  public InlineResponse20011 addCampaignPerformanceItem(InlineResponse20011CampaignPerformance campaignPerformanceItem) {
    if (this.campaignPerformance == null) {
      this.campaignPerformance = new ArrayList<InlineResponse20011CampaignPerformance>();
    }
    this.campaignPerformance.add(campaignPerformanceItem);
    return this;
  }

   /**
   * Get campaignPerformance
   * @return campaignPerformance
  **/
  @Schema(description = "")
  public List<InlineResponse20011CampaignPerformance> getCampaignPerformance() {
    return campaignPerformance;
  }

  public void setCampaignPerformance(List<InlineResponse20011CampaignPerformance> campaignPerformance) {
    this.campaignPerformance = campaignPerformance;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20011 inlineResponse20011 = (InlineResponse20011) o;
    return Objects.equals(this.sessiontoken, inlineResponse20011.sessiontoken) &&
        Objects.equals(this.merId, inlineResponse20011.merId) &&
        Objects.equals(this.walletBalance, inlineResponse20011.walletBalance) &&
        Objects.equals(this.totalCustomers, inlineResponse20011.totalCustomers) &&
        Objects.equals(this.depositSpendRatio, inlineResponse20011.depositSpendRatio) &&
        Objects.equals(this.campaignRedemptionStats, inlineResponse20011.campaignRedemptionStats) &&
        Objects.equals(this.customerStats, inlineResponse20011.customerStats) &&
        Objects.equals(this.newCustomersByMonth, inlineResponse20011.newCustomersByMonth) &&
        Objects.equals(this.campaignPerformance, inlineResponse20011.campaignPerformance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessiontoken, merId, walletBalance, totalCustomers, depositSpendRatio, campaignRedemptionStats, customerStats, newCustomersByMonth, campaignPerformance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20011 {\n");

    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("    walletBalance: ").append(toIndentedString(walletBalance)).append("\n");
    sb.append("    totalCustomers: ").append(toIndentedString(totalCustomers)).append("\n");
    sb.append("    depositSpendRatio: ").append(toIndentedString(depositSpendRatio)).append("\n");
    sb.append("    campaignRedemptionStats: ").append(toIndentedString(campaignRedemptionStats)).append("\n");
    sb.append("    customerStats: ").append(toIndentedString(customerStats)).append("\n");
    sb.append("    newCustomersByMonth: ").append(toIndentedString(newCustomersByMonth)).append("\n");
    sb.append("    campaignPerformance: ").append(toIndentedString(campaignPerformance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
