/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse20011CampaignPerformance
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class InlineResponse20011CampaignPerformance {
  @SerializedName("campaign_id")
  private String campaignId = null;

  @SerializedName("bonus_amt")
  private String bonusAmt = null;

  @SerializedName("top_up_amt")
  private String topUpAmt = null;

  @SerializedName("total_topup_amt")
  private String totalTopupAmt = null;

  @SerializedName("total_bonus_amt")
  private String totalBonusAmt = null;

  @SerializedName("top_up_count_by_month")
  private List<InlineResponse20011TopUpCountByMonth> topUpCountByMonth = null;

  @SerializedName("cashback_points")
  private List<InlineResponse20011CashbackPoints> cashbackPoints = null;

  public InlineResponse20011CampaignPerformance campaignId(String campaignId) {
    this.campaignId = campaignId;
    return this;
  }

   /**
   * Get campaignId
   * @return campaignId
  **/
  @Schema(description = "")
  public String getCampaignId() {
    return campaignId;
  }

  public void setCampaignId(String campaignId) {
    this.campaignId = campaignId;
  }

  public InlineResponse20011CampaignPerformance bonusAmt(String bonusAmt) {
    this.bonusAmt = bonusAmt;
    return this;
  }

   /**
   * Get bonusAmt
   * @return bonusAmt
  **/
  @Schema(description = "")
  public String getBonusAmt() {
    return bonusAmt;
  }

  public void setBonusAmt(String bonusAmt) {
    this.bonusAmt = bonusAmt;
  }

  public InlineResponse20011CampaignPerformance topUpAmt(String topUpAmt) {
    this.topUpAmt = topUpAmt;
    return this;
  }

   /**
   * Get topUpAmt
   * @return topUpAmt
  **/
  @Schema(description = "")
  public String getTopUpAmt() {
    return topUpAmt;
  }

  public void setTopUpAmt(String topUpAmt) {
    this.topUpAmt = topUpAmt;
  }

  public InlineResponse20011CampaignPerformance totalTopupAmt(String totalTopupAmt) {
    this.totalTopupAmt = totalTopupAmt;
    return this;
  }

   /**
   * Get totalTopupAmt
   * @return totalTopupAmt
  **/
  @Schema(description = "")
  public String getTotalTopupAmt() {
    return totalTopupAmt;
  }

  public void setTotalTopupAmt(String totalTopupAmt) {
    this.totalTopupAmt = totalTopupAmt;
  }

  public InlineResponse20011CampaignPerformance totalBonusAmt(String totalBonusAmt) {
    this.totalBonusAmt = totalBonusAmt;
    return this;
  }

   /**
   * Get totalBonusAmt
   * @return totalBonusAmt
  **/
  @Schema(description = "")
  public String getTotalBonusAmt() {
    return totalBonusAmt;
  }

  public void setTotalBonusAmt(String totalBonusAmt) {
    this.totalBonusAmt = totalBonusAmt;
  }

  public InlineResponse20011CampaignPerformance topUpCountByMonth(List<InlineResponse20011TopUpCountByMonth> topUpCountByMonth) {
    this.topUpCountByMonth = topUpCountByMonth;
    return this;
  }

  public InlineResponse20011CampaignPerformance addTopUpCountByMonthItem(InlineResponse20011TopUpCountByMonth topUpCountByMonthItem) {
    if (this.topUpCountByMonth == null) {
      this.topUpCountByMonth = new ArrayList<InlineResponse20011TopUpCountByMonth>();
    }
    this.topUpCountByMonth.add(topUpCountByMonthItem);
    return this;
  }

   /**
   * Get topUpCountByMonth
   * @return topUpCountByMonth
  **/
  @Schema(description = "")
  public List<InlineResponse20011TopUpCountByMonth> getTopUpCountByMonth() {
    return topUpCountByMonth;
  }

  public void setTopUpCountByMonth(List<InlineResponse20011TopUpCountByMonth> topUpCountByMonth) {
    this.topUpCountByMonth = topUpCountByMonth;
  }

  public InlineResponse20011CampaignPerformance cashbackPoints(List<InlineResponse20011CashbackPoints> cashbackPoints) {
    this.cashbackPoints = cashbackPoints;
    return this;
  }

  public InlineResponse20011CampaignPerformance addCashbackPointsItem(InlineResponse20011CashbackPoints cashbackPointsItem) {
    if (this.cashbackPoints == null) {
      this.cashbackPoints = new ArrayList<InlineResponse20011CashbackPoints>();
    }
    this.cashbackPoints.add(cashbackPointsItem);
    return this;
  }

   /**
   * Get cashbackPoints
   * @return cashbackPoints
  **/
  @Schema(description = "")
  public List<InlineResponse20011CashbackPoints> getCashbackPoints() {
    return cashbackPoints;
  }

  public void setCashbackPoints(List<InlineResponse20011CashbackPoints> cashbackPoints) {
    this.cashbackPoints = cashbackPoints;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20011CampaignPerformance inlineResponse20011CampaignPerformance = (InlineResponse20011CampaignPerformance) o;
    return Objects.equals(this.campaignId, inlineResponse20011CampaignPerformance.campaignId) &&
        Objects.equals(this.bonusAmt, inlineResponse20011CampaignPerformance.bonusAmt) &&
        Objects.equals(this.topUpAmt, inlineResponse20011CampaignPerformance.topUpAmt) &&
        Objects.equals(this.totalTopupAmt, inlineResponse20011CampaignPerformance.totalTopupAmt) &&
        Objects.equals(this.totalBonusAmt, inlineResponse20011CampaignPerformance.totalBonusAmt) &&
        Objects.equals(this.topUpCountByMonth, inlineResponse20011CampaignPerformance.topUpCountByMonth) &&
        Objects.equals(this.cashbackPoints, inlineResponse20011CampaignPerformance.cashbackPoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaignId, bonusAmt, topUpAmt, totalTopupAmt, totalBonusAmt, topUpCountByMonth, cashbackPoints);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20011CampaignPerformance {\n");

    sb.append("    campaignId: ").append(toIndentedString(campaignId)).append("\n");
    sb.append("    bonusAmt: ").append(toIndentedString(bonusAmt)).append("\n");
    sb.append("    topUpAmt: ").append(toIndentedString(topUpAmt)).append("\n");
    sb.append("    totalTopupAmt: ").append(toIndentedString(totalTopupAmt)).append("\n");
    sb.append("    totalBonusAmt: ").append(toIndentedString(totalBonusAmt)).append("\n");
    sb.append("    topUpCountByMonth: ").append(toIndentedString(topUpCountByMonth)).append("\n");
    sb.append("    cashbackPoints: ").append(toIndentedString(cashbackPoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
