/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.13.2
 * Contact: contact@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * MerchantcampaignppcupdatemCashcampaigns
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-19T07:17:58.745Z[GMT]")
public class MerchantcampaignppcupdatemCashcampaigns {
  @SerializedName("campaignid")
  private String campaignid = null;

  @SerializedName("topupamt")
  private String topupamt = null;

  @SerializedName("topupbonus")
  private String topupbonus = null;

  @SerializedName("activeDate")
  private String activeDate = null;

  @SerializedName("expiryDate")
  private String expiryDate = null;

  @SerializedName("isActive")
  private Boolean isActive = null;

  public MerchantcampaignppcupdatemCashcampaigns campaignid(String campaignid) {
    this.campaignid = campaignid;
    return this;
  }

   /**
   * Get campaignid
   * @return campaignid
  **/
  @Schema(description = "")
  public String getCampaignid() {
    return campaignid;
  }

  public void setCampaignid(String campaignid) {
    this.campaignid = campaignid;
  }

  public MerchantcampaignppcupdatemCashcampaigns topupamt(String topupamt) {
    this.topupamt = topupamt;
    return this;
  }

   /**
   * Get topupamt
   * @return topupamt
  **/
  @Schema(description = "")
  public String getTopupamt() {
    return topupamt;
  }

  public void setTopupamt(String topupamt) {
    this.topupamt = topupamt;
  }

  public MerchantcampaignppcupdatemCashcampaigns topupbonus(String topupbonus) {
    this.topupbonus = topupbonus;
    return this;
  }

   /**
   * Get topupbonus
   * @return topupbonus
  **/
  @Schema(description = "")
  public String getTopupbonus() {
    return topupbonus;
  }

  public void setTopupbonus(String topupbonus) {
    this.topupbonus = topupbonus;
  }

  public MerchantcampaignppcupdatemCashcampaigns activeDate(String activeDate) {
    this.activeDate = activeDate;
    return this;
  }

   /**
   * Get activeDate
   * @return activeDate
  **/
  @Schema(description = "")
  public String getActiveDate() {
    return activeDate;
  }

  public void setActiveDate(String activeDate) {
    this.activeDate = activeDate;
  }

  public MerchantcampaignppcupdatemCashcampaigns expiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * Get expiryDate
   * @return expiryDate
  **/
  @Schema(description = "")
  public String getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
  }

  public MerchantcampaignppcupdatemCashcampaigns isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

   /**
   * Get isActive
   * @return isActive
  **/
  @Schema(description = "")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantcampaignppcupdatemCashcampaigns merchantcampaignppcupdatemCashcampaigns = (MerchantcampaignppcupdatemCashcampaigns) o;
    return Objects.equals(this.campaignid, merchantcampaignppcupdatemCashcampaigns.campaignid) &&
        Objects.equals(this.topupamt, merchantcampaignppcupdatemCashcampaigns.topupamt) &&
        Objects.equals(this.topupbonus, merchantcampaignppcupdatemCashcampaigns.topupbonus) &&
        Objects.equals(this.activeDate, merchantcampaignppcupdatemCashcampaigns.activeDate) &&
        Objects.equals(this.expiryDate, merchantcampaignppcupdatemCashcampaigns.expiryDate) &&
        Objects.equals(this.isActive, merchantcampaignppcupdatemCashcampaigns.isActive);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaignid, topupamt, topupbonus, activeDate, expiryDate, isActive);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantcampaignppcupdatemCashcampaigns {\n");

    sb.append("    campaignid: ").append(toIndentedString(campaignid)).append("\n");
    sb.append("    topupamt: ").append(toIndentedString(topupamt)).append("\n");
    sb.append("    topupbonus: ").append(toIndentedString(topupbonus)).append("\n");
    sb.append("    activeDate: ").append(toIndentedString(activeDate)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
