/*
 * Corals app
 * Corals openAPI file
 *
 * OpenAPI spec version: 0.0.10
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * PurchasedVouchers
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-25T13:49:28.835Z")
public class PurchasedVouchers {
  @SerializedName("cust_voucher_id")
  private String custVoucherId = null;

  @SerializedName("purchase_dttm")
  private String purchaseDttm = null;

  public PurchasedVouchers custVoucherId(String custVoucherId) {
    this.custVoucherId = custVoucherId;
    return this;
  }

   /**
   * Get custVoucherId
   * @return custVoucherId
  **/
 @Schema(description = "")
  public String getCustVoucherId() {
    return custVoucherId;
  }

  public void setCustVoucherId(String custVoucherId) {
    this.custVoucherId = custVoucherId;
  }

  public PurchasedVouchers purchaseDttm(String purchaseDttm) {
    this.purchaseDttm = purchaseDttm;
    return this;
  }

   /**
   * Get purchaseDttm
   * @return purchaseDttm
  **/
 @Schema(description = "")
  public String getPurchaseDttm() {
    return purchaseDttm;
  }

  public void setPurchaseDttm(String purchaseDttm) {
    this.purchaseDttm = purchaseDttm;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PurchasedVouchers purchasedVouchers = (PurchasedVouchers) o;
    return Objects.equals(this.custVoucherId, purchasedVouchers.custVoucherId) &&
        Objects.equals(this.purchaseDttm, purchasedVouchers.purchaseDttm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(custVoucherId, purchaseDttm);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PurchasedVouchers {\n");
    
    sb.append("    custVoucherId: ").append(toIndentedString(custVoucherId)).append("\n");
    sb.append("    purchaseDttm: ").append(toIndentedString(purchaseDttm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

