/*
 * Corals app
 * Corals openAPI file
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * RedeemVoucher
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-10T11:04:04.220Z")
public class RedeemVoucher {
  @SerializedName("mer_cb_redeem_id")
  private String merCbRedeemId = null;

  @SerializedName("redeem_activedays")
  private String redeemActivedays = null;

  @SerializedName("redeem_activedt")
  private String redeemActivedt = null;

  @SerializedName("redeem_acttime")
  private String redeemActtime = null;

  @SerializedName("redeem_deposit_amt")
  private String redeemDepositAmt = null;

  @SerializedName("redeem_description")
  private String redeemDescription = null;

  @SerializedName("redeem_endtime")
  private String redeemEndtime = null;

  @SerializedName("redeem_expdt")
  private String redeemExpdt = null;

  @SerializedName("redeem_grps")
  private List<RedeemGrp> redeemGrps = null;

  @SerializedName("redeem_points")
  private String redeemPoints = null;

  @SerializedName("redeem_title")
  private String redeemTitle = null;

  @SerializedName("redeem_type")
  private String redeemType = null;

  @SerializedName("voucher_bg")
  private String voucherBg = null;

  @SerializedName("lead_title")
  private String leadTitle = null;

  @SerializedName("lead_description")
  private String leadDescription = null;

  @SerializedName("terms_and_conditions")
  private String termsAndConditions = null;

  @SerializedName("referal_award")
  private String referalAward = null;

  @SerializedName("assigned_voucher_id")
  private String assignedVoucherId = null;

  @SerializedName("is_cust_sharable")
  private Boolean isCustSharable = null;

  @SerializedName("max_redemption_allowed")
  private String maxRedemptionAllowed = null;

  @SerializedName("assigned_voucher_count")
  private String assignedVoucherCount = null;

  @SerializedName("is_active")
  private Boolean isActive = null;

  @SerializedName("voucher_purchase_amount")
  private String voucherPurchaseAmount = null;

  @SerializedName("is_only_for_new_cust")
  private String isOnlyForNewCust = null;

  @SerializedName("referral_reward_points")
  private String referralRewardPoints = null;

  @SerializedName("purchased_voucher_id")
  private String purchasedVoucherId = null;

  @SerializedName("purchased_voucher_purchased_date")
  private String purchasedVoucherPurchasedDate = null;

  public RedeemVoucher merCbRedeemId(String merCbRedeemId) {
    this.merCbRedeemId = merCbRedeemId;
    return this;
  }

   /**
   * Get merCbRedeemId
   * @return merCbRedeemId
  **/
  @Schema(description = "")
  public String getMerCbRedeemId() {
    return merCbRedeemId;
  }

  public void setMerCbRedeemId(String merCbRedeemId) {
    this.merCbRedeemId = merCbRedeemId;
  }

  public RedeemVoucher redeemActivedays(String redeemActivedays) {
    this.redeemActivedays = redeemActivedays;
    return this;
  }

   /**
   * Get redeemActivedays
   * @return redeemActivedays
  **/
  @Schema(description = "")
  public String getRedeemActivedays() {
    return redeemActivedays;
  }

  public void setRedeemActivedays(String redeemActivedays) {
    this.redeemActivedays = redeemActivedays;
  }

  public RedeemVoucher redeemActivedt(String redeemActivedt) {
    this.redeemActivedt = redeemActivedt;
    return this;
  }

   /**
   * Get redeemActivedt
   * @return redeemActivedt
  **/
  @Schema(description = "")
  public String getRedeemActivedt() {
    return redeemActivedt;
  }

  public void setRedeemActivedt(String redeemActivedt) {
    this.redeemActivedt = redeemActivedt;
  }

  public RedeemVoucher redeemActtime(String redeemActtime) {
    this.redeemActtime = redeemActtime;
    return this;
  }

   /**
   * Get redeemActtime
   * @return redeemActtime
  **/
  @Schema(description = "")
  public String getRedeemActtime() {
    return redeemActtime;
  }

  public void setRedeemActtime(String redeemActtime) {
    this.redeemActtime = redeemActtime;
  }

  public RedeemVoucher redeemDepositAmt(String redeemDepositAmt) {
    this.redeemDepositAmt = redeemDepositAmt;
    return this;
  }

   /**
   * Get redeemDepositAmt
   * @return redeemDepositAmt
  **/
  @Schema(description = "")
  public String getRedeemDepositAmt() {
    return redeemDepositAmt;
  }

  public void setRedeemDepositAmt(String redeemDepositAmt) {
    this.redeemDepositAmt = redeemDepositAmt;
  }

  public RedeemVoucher redeemDescription(String redeemDescription) {
    this.redeemDescription = redeemDescription;
    return this;
  }

   /**
   * Get redeemDescription
   * @return redeemDescription
  **/
  @Schema(description = "")
  public String getRedeemDescription() {
    return redeemDescription;
  }

  public void setRedeemDescription(String redeemDescription) {
    this.redeemDescription = redeemDescription;
  }

  public RedeemVoucher redeemEndtime(String redeemEndtime) {
    this.redeemEndtime = redeemEndtime;
    return this;
  }

   /**
   * Get redeemEndtime
   * @return redeemEndtime
  **/
  @Schema(description = "")
  public String getRedeemEndtime() {
    return redeemEndtime;
  }

  public void setRedeemEndtime(String redeemEndtime) {
    this.redeemEndtime = redeemEndtime;
  }

  public RedeemVoucher redeemExpdt(String redeemExpdt) {
    this.redeemExpdt = redeemExpdt;
    return this;
  }

   /**
   * Get redeemExpdt
   * @return redeemExpdt
  **/
  @Schema(description = "")
  public String getRedeemExpdt() {
    return redeemExpdt;
  }

  public void setRedeemExpdt(String redeemExpdt) {
    this.redeemExpdt = redeemExpdt;
  }

  public RedeemVoucher redeemGrps(List<RedeemGrp> redeemGrps) {
    this.redeemGrps = redeemGrps;
    return this;
  }

  public RedeemVoucher addRedeemGrpsItem(RedeemGrp redeemGrpsItem) {
    if (this.redeemGrps == null) {
      this.redeemGrps = new ArrayList<RedeemGrp>();
    }
    this.redeemGrps.add(redeemGrpsItem);
    return this;
  }

   /**
   * Get redeemGrps
   * @return redeemGrps
  **/
  @Schema(description = "")
  public List<RedeemGrp> getRedeemGrps() {
    return redeemGrps;
  }

  public void setRedeemGrps(List<RedeemGrp> redeemGrps) {
    this.redeemGrps = redeemGrps;
  }

  public RedeemVoucher redeemPoints(String redeemPoints) {
    this.redeemPoints = redeemPoints;
    return this;
  }

   /**
   * Get redeemPoints
   * @return redeemPoints
  **/
  @Schema(description = "")
  public String getRedeemPoints() {
    return redeemPoints;
  }

  public void setRedeemPoints(String redeemPoints) {
    this.redeemPoints = redeemPoints;
  }

  public RedeemVoucher redeemTitle(String redeemTitle) {
    this.redeemTitle = redeemTitle;
    return this;
  }

   /**
   * Get redeemTitle
   * @return redeemTitle
  **/
  @Schema(description = "")
  public String getRedeemTitle() {
    return redeemTitle;
  }

  public void setRedeemTitle(String redeemTitle) {
    this.redeemTitle = redeemTitle;
  }

  public RedeemVoucher redeemType(String redeemType) {
    this.redeemType = redeemType;
    return this;
  }

   /**
   * Get redeemType
   * @return redeemType
  **/
  @Schema(description = "")
  public String getRedeemType() {
    return redeemType;
  }

  public void setRedeemType(String redeemType) {
    this.redeemType = redeemType;
  }

  public RedeemVoucher voucherBg(String voucherBg) {
    this.voucherBg = voucherBg;
    return this;
  }

   /**
   * Get voucherBg
   * @return voucherBg
  **/
  @Schema(description = "")
  public String getVoucherBg() {
    return voucherBg;
  }

  public void setVoucherBg(String voucherBg) {
    this.voucherBg = voucherBg;
  }

  public RedeemVoucher leadTitle(String leadTitle) {
    this.leadTitle = leadTitle;
    return this;
  }

   /**
   * Get leadTitle
   * @return leadTitle
  **/
  @Schema(description = "")
  public String getLeadTitle() {
    return leadTitle;
  }

  public void setLeadTitle(String leadTitle) {
    this.leadTitle = leadTitle;
  }

  public RedeemVoucher leadDescription(String leadDescription) {
    this.leadDescription = leadDescription;
    return this;
  }

   /**
   * Get leadDescription
   * @return leadDescription
  **/
  @Schema(description = "")
  public String getLeadDescription() {
    return leadDescription;
  }

  public void setLeadDescription(String leadDescription) {
    this.leadDescription = leadDescription;
  }

  public RedeemVoucher termsAndConditions(String termsAndConditions) {
    this.termsAndConditions = termsAndConditions;
    return this;
  }

   /**
   * Get termsAndConditions
   * @return termsAndConditions
  **/
  @Schema(description = "")
  public String getTermsAndConditions() {
    return termsAndConditions;
  }

  public void setTermsAndConditions(String termsAndConditions) {
    this.termsAndConditions = termsAndConditions;
  }

  public RedeemVoucher referalAward(String referalAward) {
    this.referalAward = referalAward;
    return this;
  }

   /**
   * Get referalAward
   * @return referalAward
  **/
  @Schema(description = "")
  public String getReferalAward() {
    return referalAward;
  }

  public void setReferalAward(String referalAward) {
    this.referalAward = referalAward;
  }

  public RedeemVoucher assignedVoucherId(String assignedVoucherId) {
    this.assignedVoucherId = assignedVoucherId;
    return this;
  }

   /**
   * Get assignedVoucherId
   * @return assignedVoucherId
  **/
  @Schema(description = "")
  public String getAssignedVoucherId() {
    return assignedVoucherId;
  }

  public void setAssignedVoucherId(String assignedVoucherId) {
    this.assignedVoucherId = assignedVoucherId;
  }

  public RedeemVoucher isCustSharable(Boolean isCustSharable) {
    this.isCustSharable = isCustSharable;
    return this;
  }

   /**
   * Get isCustSharable
   * @return isCustSharable
  **/
  @Schema(description = "")
  public Boolean isIsCustSharable() {
    return isCustSharable;
  }

  public void setIsCustSharable(Boolean isCustSharable) {
    this.isCustSharable = isCustSharable;
  }

  public RedeemVoucher maxRedemptionAllowed(String maxRedemptionAllowed) {
    this.maxRedemptionAllowed = maxRedemptionAllowed;
    return this;
  }

   /**
   * Get maxRedemptionAllowed
   * @return maxRedemptionAllowed
  **/
  @Schema(description = "")
  public String getMaxRedemptionAllowed() {
    return maxRedemptionAllowed;
  }

  public void setMaxRedemptionAllowed(String maxRedemptionAllowed) {
    this.maxRedemptionAllowed = maxRedemptionAllowed;
  }

  public RedeemVoucher assignedVoucherCount(String assignedVoucherCount) {
    this.assignedVoucherCount = assignedVoucherCount;
    return this;
  }

   /**
   * Get assignedVoucherCount
   * @return assignedVoucherCount
  **/
  @Schema(description = "")
  public String getAssignedVoucherCount() {
    return assignedVoucherCount;
  }

  public void setAssignedVoucherCount(String assignedVoucherCount) {
    this.assignedVoucherCount = assignedVoucherCount;
  }

  public RedeemVoucher isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

   /**
   * Get isActive
   * @return isActive
  **/
  @Schema(description = "")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public RedeemVoucher voucherPurchaseAmount(String voucherPurchaseAmount) {
    this.voucherPurchaseAmount = voucherPurchaseAmount;
    return this;
  }

   /**
   * Get voucherPurchaseAmount
   * @return voucherPurchaseAmount
  **/
  @Schema(description = "")
  public String getVoucherPurchaseAmount() {
    return voucherPurchaseAmount;
  }

  public void setVoucherPurchaseAmount(String voucherPurchaseAmount) {
    this.voucherPurchaseAmount = voucherPurchaseAmount;
  }

  public RedeemVoucher isOnlyForNewCust(String isOnlyForNewCust) {
    this.isOnlyForNewCust = isOnlyForNewCust;
    return this;
  }

   /**
   * Get isOnlyForNewCust
   * @return isOnlyForNewCust
  **/
  @Schema(description = "")
  public String getIsOnlyForNewCust() {
    return isOnlyForNewCust;
  }

  public void setIsOnlyForNewCust(String isOnlyForNewCust) {
    this.isOnlyForNewCust = isOnlyForNewCust;
  }

  public RedeemVoucher referralRewardPoints(String referralRewardPoints) {
    this.referralRewardPoints = referralRewardPoints;
    return this;
  }

   /**
   * Get referralRewardPoints
   * @return referralRewardPoints
  **/
  @Schema(description = "")
  public String getReferralRewardPoints() {
    return referralRewardPoints;
  }

  public void setReferralRewardPoints(String referralRewardPoints) {
    this.referralRewardPoints = referralRewardPoints;
  }

  public RedeemVoucher purchasedVoucherId(String purchasedVoucherId) {
    this.purchasedVoucherId = purchasedVoucherId;
    return this;
  }

   /**
   * Get purchasedVoucherId
   * @return purchasedVoucherId
  **/
  @Schema(description = "")
  public String getPurchasedVoucherId() {
    return purchasedVoucherId;
  }

  public void setPurchasedVoucherId(String purchasedVoucherId) {
    this.purchasedVoucherId = purchasedVoucherId;
  }

  public RedeemVoucher purchasedVoucherPurchasedDate(String purchasedVoucherPurchasedDate) {
    this.purchasedVoucherPurchasedDate = purchasedVoucherPurchasedDate;
    return this;
  }

   /**
   * Get purchasedVoucherPurchasedDate
   * @return purchasedVoucherPurchasedDate
  **/
  @Schema(description = "")
  public String getPurchasedVoucherPurchasedDate() {
    return purchasedVoucherPurchasedDate;
  }

  public void setPurchasedVoucherPurchasedDate(String purchasedVoucherPurchasedDate) {
    this.purchasedVoucherPurchasedDate = purchasedVoucherPurchasedDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RedeemVoucher redeemVoucher = (RedeemVoucher) o;
    return Objects.equals(this.merCbRedeemId, redeemVoucher.merCbRedeemId) &&
        Objects.equals(this.redeemActivedays, redeemVoucher.redeemActivedays) &&
        Objects.equals(this.redeemActivedt, redeemVoucher.redeemActivedt) &&
        Objects.equals(this.redeemActtime, redeemVoucher.redeemActtime) &&
        Objects.equals(this.redeemDepositAmt, redeemVoucher.redeemDepositAmt) &&
        Objects.equals(this.redeemDescription, redeemVoucher.redeemDescription) &&
        Objects.equals(this.redeemEndtime, redeemVoucher.redeemEndtime) &&
        Objects.equals(this.redeemExpdt, redeemVoucher.redeemExpdt) &&
        Objects.equals(this.redeemGrps, redeemVoucher.redeemGrps) &&
        Objects.equals(this.redeemPoints, redeemVoucher.redeemPoints) &&
        Objects.equals(this.redeemTitle, redeemVoucher.redeemTitle) &&
        Objects.equals(this.redeemType, redeemVoucher.redeemType) &&
        Objects.equals(this.voucherBg, redeemVoucher.voucherBg) &&
        Objects.equals(this.leadTitle, redeemVoucher.leadTitle) &&
        Objects.equals(this.leadDescription, redeemVoucher.leadDescription) &&
        Objects.equals(this.termsAndConditions, redeemVoucher.termsAndConditions) &&
        Objects.equals(this.referalAward, redeemVoucher.referalAward) &&
        Objects.equals(this.assignedVoucherId, redeemVoucher.assignedVoucherId) &&
        Objects.equals(this.isCustSharable, redeemVoucher.isCustSharable) &&
        Objects.equals(this.maxRedemptionAllowed, redeemVoucher.maxRedemptionAllowed) &&
        Objects.equals(this.assignedVoucherCount, redeemVoucher.assignedVoucherCount) &&
        Objects.equals(this.isActive, redeemVoucher.isActive) &&
        Objects.equals(this.voucherPurchaseAmount, redeemVoucher.voucherPurchaseAmount) &&
        Objects.equals(this.isOnlyForNewCust, redeemVoucher.isOnlyForNewCust) &&
        Objects.equals(this.referralRewardPoints, redeemVoucher.referralRewardPoints) &&
        Objects.equals(this.purchasedVoucherId, redeemVoucher.purchasedVoucherId) &&
        Objects.equals(this.purchasedVoucherPurchasedDate, redeemVoucher.purchasedVoucherPurchasedDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merCbRedeemId, redeemActivedays, redeemActivedt, redeemActtime, redeemDepositAmt, redeemDescription, redeemEndtime, redeemExpdt, redeemGrps, redeemPoints, redeemTitle, redeemType, voucherBg, leadTitle, leadDescription, termsAndConditions, referalAward, assignedVoucherId, isCustSharable, maxRedemptionAllowed, assignedVoucherCount, isActive, voucherPurchaseAmount, isOnlyForNewCust, referralRewardPoints, purchasedVoucherId, purchasedVoucherPurchasedDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RedeemVoucher {\n");
    
    sb.append("    merCbRedeemId: ").append(toIndentedString(merCbRedeemId)).append("\n");
    sb.append("    redeemActivedays: ").append(toIndentedString(redeemActivedays)).append("\n");
    sb.append("    redeemActivedt: ").append(toIndentedString(redeemActivedt)).append("\n");
    sb.append("    redeemActtime: ").append(toIndentedString(redeemActtime)).append("\n");
    sb.append("    redeemDepositAmt: ").append(toIndentedString(redeemDepositAmt)).append("\n");
    sb.append("    redeemDescription: ").append(toIndentedString(redeemDescription)).append("\n");
    sb.append("    redeemEndtime: ").append(toIndentedString(redeemEndtime)).append("\n");
    sb.append("    redeemExpdt: ").append(toIndentedString(redeemExpdt)).append("\n");
    sb.append("    redeemGrps: ").append(toIndentedString(redeemGrps)).append("\n");
    sb.append("    redeemPoints: ").append(toIndentedString(redeemPoints)).append("\n");
    sb.append("    redeemTitle: ").append(toIndentedString(redeemTitle)).append("\n");
    sb.append("    redeemType: ").append(toIndentedString(redeemType)).append("\n");
    sb.append("    voucherBg: ").append(toIndentedString(voucherBg)).append("\n");
    sb.append("    leadTitle: ").append(toIndentedString(leadTitle)).append("\n");
    sb.append("    leadDescription: ").append(toIndentedString(leadDescription)).append("\n");
    sb.append("    termsAndConditions: ").append(toIndentedString(termsAndConditions)).append("\n");
    sb.append("    referalAward: ").append(toIndentedString(referalAward)).append("\n");
    sb.append("    assignedVoucherId: ").append(toIndentedString(assignedVoucherId)).append("\n");
    sb.append("    isCustSharable: ").append(toIndentedString(isCustSharable)).append("\n");
    sb.append("    maxRedemptionAllowed: ").append(toIndentedString(maxRedemptionAllowed)).append("\n");
    sb.append("    assignedVoucherCount: ").append(toIndentedString(assignedVoucherCount)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    voucherPurchaseAmount: ").append(toIndentedString(voucherPurchaseAmount)).append("\n");
    sb.append("    isOnlyForNewCust: ").append(toIndentedString(isOnlyForNewCust)).append("\n");
    sb.append("    referralRewardPoints: ").append(toIndentedString(referralRewardPoints)).append("\n");
    sb.append("    purchasedVoucherId: ").append(toIndentedString(purchasedVoucherId)).append("\n");
    sb.append("    purchasedVoucherPurchasedDate: ").append(toIndentedString(purchasedVoucherPurchasedDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

