/*
 * Corals app
 * Corals openAPI file
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package life.corals.merchant.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * VoucherManageResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-04T06:10:25.919Z")
public class VoucherManageResponse {
  @SerializedName("status_code")
  private String statusCode = null;

  @SerializedName("status_message")
  private String statusMessage = null;

  @SerializedName("cust_name")
  private String custName = null;

  @SerializedName("cust_id")
  private String custId = null;

  @SerializedName("redeem_message")
  private String redeemMessage = null;

  @SerializedName("referral_reward")
  private String referralReward = null;

  public VoucherManageResponse statusCode(String statusCode) {
    this.statusCode = statusCode;
    return this;
  }

   /**
   * Get statusCode
   * @return statusCode
  **/
  @Schema(description = "")
  public String getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(String statusCode) {
    this.statusCode = statusCode;
  }

  public VoucherManageResponse statusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
    return this;
  }

   /**
   * Get statusMessage
   * @return statusMessage
  **/
   @Schema(description = "")
  public String getStatusMessage() {
    return statusMessage;
  }

  public void setStatusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
  }

  public VoucherManageResponse custName(String custName) {
    this.custName = custName;
    return this;
  }

   /**
   * Get custName
   * @return custName
  **/
   @Schema(description = "")
  public String getCustName() {
    return custName;
  }

  public void setCustName(String custName) {
    this.custName = custName;
  }

  public VoucherManageResponse custId(String custId) {
    this.custId = custId;
    return this;
  }

   /**
   * Get custId
   * @return custId
  **/
   @Schema(description = "")
  public String getCustId() {
    return custId;
  }

  public void setCustId(String custId) {
    this.custId = custId;
  }

  public VoucherManageResponse redeemMessage(String redeemMessage) {
    this.redeemMessage = redeemMessage;
    return this;
  }

   /**
   * Get redeemMessage
   * @return redeemMessage
  **/
   @Schema(description = "")
  public String getRedeemMessage() {
    return redeemMessage;
  }

  public void setRedeemMessage(String redeemMessage) {
    this.redeemMessage = redeemMessage;
  }

  public VoucherManageResponse referralReward(String referralReward) {
    this.referralReward = referralReward;
    return this;
  }

   /**
   * Get referralReward
   * @return referralReward
  **/
   @Schema(description = "")
  public String getReferralReward() {
    return referralReward;
  }

  public void setReferralReward(String referralReward) {
    this.referralReward = referralReward;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VoucherManageResponse voucherManageResponse = (VoucherManageResponse) o;
    return Objects.equals(this.statusCode, voucherManageResponse.statusCode) &&
        Objects.equals(this.statusMessage, voucherManageResponse.statusMessage) &&
        Objects.equals(this.custName, voucherManageResponse.custName) &&
        Objects.equals(this.custId, voucherManageResponse.custId) &&
        Objects.equals(this.redeemMessage, voucherManageResponse.redeemMessage) &&
        Objects.equals(this.referralReward, voucherManageResponse.referralReward);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statusCode, statusMessage, custName, custId, redeemMessage, referralReward);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VoucherManageResponse {\n");
    
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    statusMessage: ").append(toIndentedString(statusMessage)).append("\n");
    sb.append("    custName: ").append(toIndentedString(custName)).append("\n");
    sb.append("    custId: ").append(toIndentedString(custId)).append("\n");
    sb.append("    redeemMessage: ").append(toIndentedString(redeemMessage)).append("\n");
    sb.append("    referralReward: ").append(toIndentedString(referralReward)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

