/*
 * Corals app
 * This version includes cashback module
 *
 * OpenAPI spec version: 1.4.0
 * Contact: gp@corals.life
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package life.corals.merchant.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
